/**
 * Geo buy-gem / rudraksha city landings → quality hubs.
 * SEO harvested from legacy WP pages; do not render as page copy.
 * Generated from _redirect_audit/old_geo_buy_seo.json
 */

export const GEO_BUY_REDIRECTS: Array<[string, string]> = [
  ['/buy-authentic-certified-rudraksha-in-california-trusted-rudraksha-dealer', '/knowledge/rudraksha-qualities'],
  ['/buy-natural-certified-blue-sapphire-gemstone-in-new-york', '/knowledge/gem-qualities/blue-sapphire'],
  ['/buy-natural-certified-blue-sapphire-in-abu-dhabi-neelam-buying-guide', '/knowledge/gem-qualities/blue-sapphire'],
  ['/buy-natural-certified-blue-sapphire-in-california-trusted-neelam-dealer', '/knowledge/gem-qualities/blue-sapphire'],
  ['/buy-natural-certified-blue-sapphire-in-texas-trusted-neelam-stone-dealer', '/knowledge/gem-qualities/blue-sapphire'],
  ['/buy-natural-certified-cats-eye-in-abu-dhabi-a-complete-buying-guide', '/knowledge/gem-qualities/catseye'],
  ['/buy-natural-certified-cats-eye-in-california-premium-lehsunia-dealer', '/knowledge/gem-qualities/catseye'],
  ['/buy-natural-certified-catseye-lehsunia-gemstone-in-new-york', '/knowledge/gem-qualities/catseye'],
  ['/buy-natural-certified-emerald-in-california-trusted-panna-stone-dealer', '/knowledge/gem-qualities/emerald'],
  ['/buy-natural-certified-emerald-panna-gemstone-in-new-york', '/knowledge/gem-qualities/emerald'],
  ['/buy-natural-certified-emeralds-in-abu-dhabi-a-complete-buying-guide', '/knowledge/gem-qualities/emerald'],
  ['/buy-natural-certified-emeralds-in-birmingham-expert-guide', '/knowledge/gem-qualities/emerald'],
  ['/buy-natural-certified-hessonite-gemstone-in-new-york-benefits-uses-buying-guide', '/knowledge/gem-qualities/hessonite'],
  ['/buy-natural-certified-hessonite-gomed-in-california-trusted-dealer', '/knowledge/gem-qualities/hessonite'],
  ['/buy-natural-certified-hessonite-in-abu-dhabi-a-complete-buying-guide', '/knowledge/gem-qualities/hessonite'],
  ['/buy-natural-certified-hessonite-in-birmingham-guide', '/knowledge/gem-qualities/hessonite'],
  ['/buy-natural-certified-opal-gemstones-in-new-york-genuine-opal-stones', '/knowledge/gem-qualities/opal'],
  ['/buy-natural-certified-opal-in-abu-dhabi-original-opal-buying-guide', '/knowledge/gem-qualities/opal'],
  ['/buy-natural-certified-opal-in-birmingham-buying-guide', '/knowledge/gem-qualities/opal'],
  ['/buy-natural-certified-opal-in-california-trusted-opal-dealer', '/knowledge/gem-qualities/opal'],
  ['/buy-natural-certified-pearl-in-birmingham-buying-guide', '/knowledge/gem-qualities/pearl'],
  ['/buy-natural-certified-pearl-in-california-trusted-pearl-dealer', '/knowledge/gem-qualities/pearl'],
  ['/buy-natural-certified-pearl-moti-gemstone-in-new-york', '/knowledge/gem-qualities/pearl'],
  ['/buy-natural-certified-pearls-in-abu-dhabi-a-complete-buying-guide', '/knowledge/gem-qualities/pearl'],
  ['/buy-natural-certified-red-coral-in-abu-dhabi-original-moonga-stone', '/knowledge/gem-qualities/red-coral'],
  ['/buy-natural-certified-red-coral-in-california-trusted-moonga-stone-dealer', '/knowledge/gem-qualities/red-coral'],
  ['/buy-natural-certified-red-coral-moonga-gemstone-in-new-york', '/knowledge/gem-qualities/red-coral'],
  ['/buy-natural-certified-ruby-in-abu-dhabi-a-smart-buyers-guide', '/knowledge/gem-qualities/ruby'],
  ['/buy-natural-certified-ruby-in-california-trusted-manik-dealer', '/knowledge/gem-qualities/ruby'],
  ['/buy-natural-certified-ruby-in-texas-genuine-manik-stone-dealer', '/knowledge/gem-qualities/ruby'],
  ['/buy-natural-certified-ruby-manik-gemstone-in-new-york', '/knowledge/gem-qualities/ruby'],
  ['/buy-natural-certified-rudraksha-in-abu-dhabi-genuine-rudraksha-beads', '/knowledge/rudraksha-qualities'],
  ['/buy-natural-certified-rudraksha-in-new-york-types-benefits-buying-guide', '/knowledge/rudraksha-qualities'],
  ['/buy-natural-certified-rudraksha-in-sharjah-complete-buying-guide', '/knowledge/rudraksha-qualities'],
  ['/buy-natural-certified-white-sapphire-gemstone-in-new-york', '/knowledge/gem-qualities/white-sapphire'],
  ['/buy-natural-certified-white-sapphire-in-abu-dhabi-a-complete-buying-guide', '/knowledge/gem-qualities/white-sapphire'],
  ['/buy-natural-certified-white-sapphire-in-birmingham-guide', '/knowledge/gem-qualities/white-sapphire'],
  ['/buy-natural-certified-white-sapphire-in-california', '/knowledge/gem-qualities/white-sapphire'],
  ['/buy-natural-certified-yellow-sapphire-in-abu-dhabi-pukhraj-buying-guide', '/knowledge/gem-qualities/yellow-sapphire'],
  ['/buy-natural-certified-yellow-sapphire-in-california-pukhraj', '/knowledge/gem-qualities/yellow-sapphire'],
  ['/buy-natural-certified-yellow-sapphire-in-texas-genuine-pukhraj-stone-dealer', '/knowledge/gem-qualities/yellow-sapphire'],
  ['/buy-natural-certified-yellow-sapphire-pukhraj-gemstone-in-new-york', '/knowledge/gem-qualities/yellow-sapphire'],
  ['/buy-original-certified-rudraksha-in-birmingham-guide', '/knowledge/rudraksha-qualities'],
  ['/cats-eye-gemstone-in-malaysia-natural-certified-ketu-stone-for-protection-spiritual-growth', '/knowledge/gem-qualities/catseye'],
  ['/cats-eye-gemstone-in-philippines-natural-certified-stone-for-protection-and-success', '/knowledge/gem-qualities/catseye'],
  ['/cats-eye-stone-in-birmingham-genuine-certified-buying-guide', '/knowledge/gem-qualities/catseye'],
  ['/find-the-perfect-natural-ruby-in-birmingham-buyers-guide', '/knowledge/gem-qualities/ruby'],
  ['/natural-certified-blue-sapphire-in-sharjah-complete-neelam-buying-guide', '/knowledge/gem-qualities/blue-sapphire'],
  ['/natural-certified-cats-eye-in-sharjah-complete-buying-guide', '/knowledge/gem-qualities/catseye'],
  ['/natural-certified-emerald-in-sharjah-complete-buying-guide', '/knowledge/gem-qualities/emerald'],
  ['/natural-certified-hessonite-in-sharjah-complete-buying-guide', '/knowledge/gem-qualities/hessonite'],
  ['/natural-certified-opal-in-sharjah-complete-buying-guide', '/knowledge/gem-qualities/opal'],
  ['/natural-certified-pearl-in-sharjah-complete-buying-guide', '/knowledge/gem-qualities/pearl'],
  ['/natural-certified-red-coral-in-birmingham-buying-guide', '/knowledge/gem-qualities/red-coral'],
  ['/natural-certified-red-coral-in-sharjah-complete-moonga-buying-guide', '/knowledge/gem-qualities/red-coral'],
  ['/natural-certified-ruby-in-sharjah-complete-ruby-buying-guide', '/knowledge/gem-qualities/ruby'],
  ['/natural-certified-white-sapphire-in-sharjah-complete-buying-guide', '/knowledge/gem-qualities/white-sapphire'],
  ['/natural-certified-yellow-sapphire-in-birmingham-expert-buying-guide', '/knowledge/gem-qualities/yellow-sapphire'],
  ['/natural-certified-yellow-sapphire-in-sharjah-complete-buying-guide', '/knowledge/gem-qualities/yellow-sapphire'],
  ['/opal-gemstone-in-malaysia-natural-certified-stone-for-love-healing-and-peace', '/knowledge/gem-qualities/opal'],
  ['/the-ultimate-guide-to-buying-natural-blue-sapphire-in-birmingham', '/knowledge/gem-qualities/blue-sapphire'],
];

export type GeoBuySource = {
  path: string;
  destination: string;
  city: string;
  title: string;
  description: string;
  h1: string;
  topics: string[];
};

export const GEO_BUY_SOURCES: GeoBuySource[] = [
  {
    path: '/buy-authentic-certified-rudraksha-in-california-trusted-rudraksha-dealer',
    destination: '/knowledge/rudraksha-qualities',
    city: 'California',
    title: 'Buy Authentic & Certified Rudraksha in California | Trusted Rudraksha Dealer',
    description: 'Buy authentic & certified Rudraksha in California from a trusted dealer. Explore original 1 Mukhi to 14 Mukhi Rudraksha, expert guidance, certification, and secure delivery across California.',
    h1: 'Buy Authentic & Certified Rudraksha in California | Complete Rudraksha Buying Guide',
    topics: ['Why Authentic Rudraksha Matters', 'Different Types of Rudraksha', 'How to Identify Genuine Rudraksha', 'Rudraksha in Traditional Vedic Practices', 'Common Mistakes to Avoid When Buying Rudraksha', 'Looking for a Trusted Rudraksha Dealer in California?'],
  },
  {
    path: '/buy-natural-certified-blue-sapphire-gemstone-in-new-york',
    destination: '/knowledge/gem-qualities/blue-sapphire',
    city: 'New York',
    title: 'Buy Natural & Certified Blue Sapphire Gemstone in New York',
    description: 'Discover natural and certified Blue Sapphire (Neelam) gemstones in New York. Learn benefits, pricing, astrology significance, and how to choose authentic, lab-certified stones for jewelry and Vedic astrology use.',
    h1: 'Buy Natural & Certified Blue Sapphire Gemstone in New York',
    topics: ['Why is Blue Sapphire Popular?', 'Natural and Certified Blue Sapphire', 'Blue Sapphire Healing and Spiritual Significance', 'Choosing the Right Blue Sapphire', 'Price and Quality', 'Conclusion'],
  },
  {
    path: '/buy-natural-certified-blue-sapphire-in-abu-dhabi-neelam-buying-guide',
    destination: '/knowledge/gem-qualities/blue-sapphire',
    city: 'Abu Dhabi',
    title: 'Buy Natural & Certified Blue Sapphire in Abu Dhabi Neelam Buying Guide',
    description: 'Buy natural & certified Blue Sapphire (Neelam) in Abu Dhabi. Learn how to verify authenticity, certification, pricing, quality, care tips, and Vedic astrology guidance before purchasing.',
    h1: 'Buy Natural & Certified Blue Sapphire in Abu Dhabi Neelam Buying Guide',
    topics: ['What Makes a Blue Sapphire Valuable?', 'Questions to Ask Before Buying', 'Why Certification is Essential', 'Common Mistakes Buyers Should Avoid', 'Blue Sapphire Price in Abu Dhabi', 'How to Care for Your Blue Sapphire'],
  },
  {
    path: '/buy-natural-certified-blue-sapphire-in-california-trusted-neelam-dealer',
    destination: '/knowledge/gem-qualities/blue-sapphire',
    city: 'California',
    title: 'Buy Natural & Certified Blue Sapphire in California | Trusted Neelam Dealer',
    description: 'Buy natural & certified Blue Sapphire (Neelam) in California from a trusted dealer. Explore Ceylon, Kashmir, Burma & Madagascar sapphires, certification, Vedic astrology guidance, and expert buying tips.',
    h1: 'Buy Natural & Certified Blue Sapphire in California | Trusted Dealer & Buying Guide',
    topics: ['Why California Buyers Prefer Certified Blue Sapphire', 'Popular Origins of Blue Sapphire', 'Best Jewellery Options for Blue Sapphire', 'Blue Sapphire and Vedic Astrology', 'Common Mistakes Buyers Should Avoid', 'Looking for a Trusted Blue Sapphire Dealer in California?'],
  },
  {
    path: '/buy-natural-certified-blue-sapphire-in-texas-trusted-neelam-stone-dealer',
    destination: '/knowledge/gem-qualities/blue-sapphire',
    city: 'Texas',
    title: 'Buy Natural & Certified Blue Sapphire in Texas | Trusted Neelam Stone Dealer',
    description: 'Buy natural & certified Blue Sapphire (Neelam) in Texas from a trusted gemstone dealer. Learn about sapphire quality, certification, origins, treatments, Vedic astrology, and expert buying tips.',
    h1: 'Buy Natural & Certified Blue Sapphire in Texas | Trusted Neelam Stone Dealer',
    topics: ['What Makes the Blue Sapphire a True Luxury of All Times', 'What Makes One Blue Sapphire More Valuable Than Another?', 'Luxury Jewellery Trends in Texas', 'How to Verify a Genuine Blue Sapphire', 'Natural vs Treated Blue Sapphire', 'Blue Sapphire in Vedic Astrology'],
  },
  {
    path: '/buy-natural-certified-cats-eye-in-abu-dhabi-a-complete-buying-guide',
    destination: '/knowledge/gem-qualities/catseye',
    city: 'Abu Dhabi',
    title: 'Buy Natural & Certified Cat\'s Eye in Abu Dhabi – A Complete Buying Guide',
    description: 'Buy natural certified catseye with Vedic astrology guidance for Abu Dhabi. Authenticity, quality tips, and Pure Vedic Gems heritage since 1937.',
    h1: 'Buy Natural & Certified Cat\'s Eye in Abu Dhabi – A Complete Buying Guide',
    topics: ['How to Identify a Genuine Cat\'s Eye', 'Why Buy a Certified Cat\'s Eye?', 'Cat\'s Eye and Vedic Astrology', 'Avoid these common mistakes:', 'Where to Buy Cat\'s Eye in Abu Dhabi?', 'What Affects Cat\'s Eye Price?'],
  },
  {
    path: '/buy-natural-certified-cats-eye-in-california-premium-lehsunia-dealer',
    destination: '/knowledge/gem-qualities/catseye',
    city: 'California',
    title: 'Buy Natural & Certified Cat\'s Eye in California | Premium Lehsunia Dealer',
    description: 'Buy natural certified catseye with Vedic astrology guidance for California. Authenticity, quality tips, and Pure Vedic Gems heritage since 1937.',
    h1: 'Buy Natural & Certified Cat\'s Eye in California | Premium Lehsunia Stone Dealer',
    topics: ['Why Choose a Certified Cat\'s Eye?', 'How to Identify a Genuine Cat\'s Eye Stone', 'Popular Origins of Cat\'s Eye', 'Cat\'s Eye and Vedic Astrology', 'Why Certification Matters', 'Looking for a Trusted Cat\'s Eye Dealer in California?'],
  },
  {
    path: '/buy-natural-certified-catseye-lehsunia-gemstone-in-new-york',
    destination: '/knowledge/gem-qualities/catseye',
    city: 'New York',
    title: 'Buy Natural & Certified Catseye (Lehsunia) Gemstone in New York',
    description: 'Buy natural and certified Catseye (Lehsunia) gemstone in New York. Explore benefits, spiritual significance, quality factors, certification importance, and expert buying tips.',
    h1: 'Buy Natural & Certified Catseye (Lehsunia) Gemstone in New York',
    topics: ['Why is Catseye Popular?', 'Why Choose a Certified Catseye?', 'Catseye Healing and Spiritual Significance', 'Choosing the Right Catseye', 'Price and Quality', 'Final Conclusion'],
  },
  {
    path: '/buy-natural-certified-emerald-in-california-trusted-panna-stone-dealer',
    destination: '/knowledge/gem-qualities/emerald',
    city: 'California',
    title: 'Buy Natural & Certified Emerald in California | Trusted Panna Stone Dealer',
    description: 'Buy natural & certified Emerald (Panna) in California from a trusted gemstone dealer. Explore Colombian, Zambian & Brazilian emeralds with certification, expert guidance, secure delivery, and transparent pricing.',
    h1: 'Buy Natural & Certified Emerald in California | Trusted Panna Stone Dealer & Buying Guide',
    topics: ['Why Emerald is One of the Most Desired Gemstones', 'Famous Origins of Natural Emerald', 'Understanding Emerald Quality', 'Emerald and Vedic Astrology', 'Common Mistakes Buyers Should Avoid', 'Looking for a Trusted Emerald Dealer in California?'],
  },
  {
    path: '/buy-natural-certified-emerald-panna-gemstone-in-new-york',
    destination: '/knowledge/gem-qualities/emerald',
    city: 'New York',
    title: 'Buy Natural & Certified Emerald (Panna) Gemstone in New York',
    description: 'Buy natural and certified Emerald (Panna) gemstones in New York. Explore benefits, healing significance, certification importance, buying tips, quality factors, and trusted sources for genuine emeralds.',
    h1: 'Buy Natural & Certified Emerald (Panna) Gemstone in New York',
    topics: ['Why is Emerald Popular?', 'Why Choose a Certified Emerald?', 'Emerald Healing and Spiritual Significance', 'Choosing the Right Emerald', 'Price and Quality', 'Conclusion'],
  },
  {
    path: '/buy-natural-certified-emeralds-in-abu-dhabi-a-complete-buying-guide',
    destination: '/knowledge/gem-qualities/emerald',
    city: 'Abu Dhabi',
    title: 'Buy Natural & Certified Emeralds in Abu Dhabi – A Complete Buying Guide',
    description: 'Buy natural & certified Emerald (Panna) in Abu Dhabi. Learn how to identify genuine emeralds, understand certification, pricing, authenticity, Vedic astrology guidance, and smart buying tips.',
    h1: 'Buy Natural & Certified Emeralds in Abu Dhabi – A Complete Buying Guide',
    topics: ['How to Determine Authentic Emeralds', 'Why Buy a Certified Emerald?', 'Emerald and Vedic Astrology', 'Typical Errors That Buyers Need to Avoid', 'Where to Buy Emerald in Abu Dhabi?', 'Factors That Influence the Price of Emerald'],
  },
  {
    path: '/buy-natural-certified-emeralds-in-birmingham-expert-guide',
    destination: '/knowledge/gem-qualities/emerald',
    city: 'Birmingham',
    title: 'Buy Natural & Certified Emeralds in Birmingham | Expert Guide',
    description: 'Buy natural & certified Emeralds in Birmingham. Learn how to identify genuine Panna, understand treatments, certification, pricing, and expert buying tips.',
    h1: 'Buy Natural & Certified Emeralds in Birmingham | Expert Buying Guide',
    topics: ['Why Emerald is One of the Most Valuable Gemstones', 'How to Choose a Genuine Emerald', 'Natural vs Treated Emerald', 'Emerald and Vedic Astrology', 'Questions to Ask Before Buying an Emerald', 'Looking for an emerald dealer in Birmingham?'],
  },
  {
    path: '/buy-natural-certified-hessonite-gemstone-in-new-york-benefits-uses-buying-guide',
    destination: '/knowledge/gem-qualities/hessonite',
    city: 'New York',
    title: 'Buy Natural & Certified Hessonite Gemstone in New York Benefits, Uses & Buying Guide',
    description: 'Buy natural and certified Hessonite (Gomed) gemstones in New York. Learn about benefits, uses, quality factors, certification, pricing, and expert buying tips.',
    h1: 'Buy Natural & Certified Hessonite Gemstone in New York Benefits, Uses & Buying Guide',
    topics: ['Why is Hessonite Popular?', 'Why Choose a Certified Hessonite?', 'Healing and Spiritual Significance', 'Choosing the Right Hessonite', 'Price and Quality', 'Conclusion'],
  },
  {
    path: '/buy-natural-certified-hessonite-gomed-in-california-trusted-dealer',
    destination: '/knowledge/gem-qualities/hessonite',
    city: 'California',
    title: 'Buy Natural & Certified Hessonite (Gomed) in California | Trusted Dealer',
    description: 'Buy Natural & Certified Hessonite (Gomed) in California. Learn how to identify genuine Hessonite, compare Ceylon, Indian & African origins, understand certification, Vedic astrology, pricing, and gemstone care before you buy.',
    h1: 'Buy Natural & Certified Hessonite in California | Trusted Gomed Stone Dealer & Buying Guide',
    topics: ['Why Hessonite is Becoming Popular in California', 'How to Identify a Genuine Hessonite', 'Popular Origins of Hessonite', 'Hessonite and Vedic Astrology', 'Mistakes to Avoid When Buying Hessonite', 'Looking for a Hessonite Dealer in California?'],
  },
  {
    path: '/buy-natural-certified-hessonite-in-abu-dhabi-a-complete-buying-guide',
    destination: '/knowledge/gem-qualities/hessonite',
    city: 'Abu Dhabi',
    title: 'Buy Natural & Certified Hessonite in Abu Dhabi – A Complete Buying Guide',
    description: 'Learn how to buy natural & certified Hessonite (Gomed) in Abu Dhabi. Discover authenticity checks, certification, pricing factors, Vedic astrology guidance, and expert buying tips.',
    h1: 'Buy Natural & Certified Hessonite in Abu Dhabi – A Complete Buying Guide',
    topics: ['How to Identify a Genuine Hessonite', 'Why Buy a Certified Hessonite?', 'Hessonite and Vedic Astrology', 'Common Mistakes Buyers Should Avoid', 'Where to Buy Hessonite in Abu Dhabi?', 'What Affects Hessonite Price?'],
  },
  {
    path: '/buy-natural-certified-hessonite-in-birmingham-guide',
    destination: '/knowledge/gem-qualities/hessonite',
    city: 'Birmingham',
    title: 'Buy Natural & Certified Hessonite in Birmingham | Guide',
    description: 'Buy natural & certified Hessonite in Birmingham with confidence. Learn about Gomed quality, certification, pricing, Vedic astrology, and expert buying tips.',
    h1: 'Buy Natural & Certified Hessonite in Birmingham | Expert Gemstone Buying Guide',
    topics: ['Why Hessonite is a Unique Gemstone', 'Key factors to think about before buying', 'Natural vs Treated Hessonite', 'Hessonite and Vedic Astrology', 'Questions to Ask Your Gemstone Dealer', 'Looking for a hessonite dealer in Birmingham?'],
  },
  {
    path: '/buy-natural-certified-opal-gemstones-in-new-york-genuine-opal-stones',
    destination: '/knowledge/gem-qualities/opal',
    city: 'New York',
    title: 'Buy Natural & Certified Opal Gemstones in New York Genuine Opal Stones',
    description: 'Buy natural and certified Opal gemstones in New York. Explore Opal benefits, spiritual significance, quality factors, certification, pricing, and buying guidance.',
    h1: 'Buy Natural & Certified Opal Gemstones in New York Benefits, Uses & Buying Guide',
    topics: ['Why is Opal Popular?', 'Why Choose a Certified Opal?', 'Opal Healing and Spiritual Significance', 'Choosing the Right Opal', 'Price and Quality', 'Conclusion'],
  },
  {
    path: '/buy-natural-certified-opal-in-abu-dhabi-original-opal-buying-guide',
    destination: '/knowledge/gem-qualities/opal',
    city: 'Abu Dhabi',
    title: 'Buy Natural & Certified Opal in Abu Dhabi | Original Opal Buying Guide',
    description: 'Looking to buy natural & certified Opal in Abu Dhabi? Learn how to identify genuine Opals, understand certification, pricing, quality factors, and Vedic astrology considerations before purchasing.',
    h1: 'Buy Natural & Certified Opal in Abu Dhabi – A Complete Buying Guide',
    topics: ['What Makes a Good Quality Opal?', 'Why Buy a Certified Opal?', 'Opal and Vedic Astrology', 'Common Mistakes Buyers Should Avoid', 'Where to Buy Opal in Abu Dhabi?', 'What Affects Opal Price?'],
  },
  {
    path: '/buy-natural-certified-opal-in-birmingham-buying-guide',
    destination: '/knowledge/gem-qualities/opal',
    city: 'Birmingham',
    title: 'Buy Natural & Certified Opal in Birmingham | Buying Guide',
    description: 'Learn how to buy natural & certified Opal in Birmingham. Discover Opal types, certification, pricing, Vedic astrology, and expert buying tips.',
    h1: 'Buy Natural & Certified Opal in Birmingham | Complete Opal Buying Guide',
    topics: ['What Makes Opal Special?', 'Types of Opal', 'How to Choose a Genuine Opal', 'Opal and Vedic Astrology', 'Questions to Ask Before Buying Opal', 'Looking for an Opal Dealer in Birmingham?'],
  },
  {
    path: '/buy-natural-certified-opal-in-california-trusted-opal-dealer',
    destination: '/knowledge/gem-qualities/opal',
    city: 'California',
    title: 'Buy Natural & Certified Opal in California | Trusted Opal Dealer',
    description: 'Buy natural & certified Opal in California from a trusted gemstone dealer. Learn about Australian, Ethiopian, Fire & White Opals, certification, quality, Vedic astrology, care tips, and safe online buying.',
    h1: 'Buy Natural & Certified Opal in California | Trusted Opal Stone Dealer & Buying Guide',
    topics: ['Differences of Opal from Other Precious Stones', 'Different Types of Natural Opal', 'How to Choose a High-Quality Opal', 'Opal and Vedic Astrology', 'Common Buying Mistakes to Avoid', 'Are you in search of an opal seller in California?'],
  },
  {
    path: '/buy-natural-certified-pearl-in-birmingham-buying-guide',
    destination: '/knowledge/gem-qualities/pearl',
    city: 'Birmingham',
    title: 'Buy Natural & Certified Pearl in Birmingham | Buying Guide',
    description: 'Discover how to buy natural & certified pearls in Birmingham. Learn about pearl types, certification, pricing, quality, Vedic astrology, and expert buying tips.',
    h1: 'Buy Natural & Certified Pearl in Birmingham | Complete Buying Guide',
    topics: ['Why Pearls Remain a Timeless Choice', 'Natural Pearl vs Cultured Pearl', 'How to Identify a Genuine Pearl', 'Pearl and Vedic Astrology', 'Questions to Ask Before Buying a Pearl', 'Looking for a Pearl Dealer in Birmingham?'],
  },
  {
    path: '/buy-natural-certified-pearl-in-california-trusted-pearl-dealer',
    destination: '/knowledge/gem-qualities/pearl',
    city: 'California',
    title: 'Buy Natural & Certified Pearl in California | Trusted Pearl Dealer',
    description: 'Buy natural & certified pearls in California from a trusted pearl dealer. Explore South Sea, Akoya, Tahitian & Freshwater pearls with expert buying guidance, certification, Vedic astrology insights, and pearl care tips.',
    h1: 'Buy Natural & Certified Pearl in California | Trusted Pearl Dealer & Buying Guide',
    topics: ['Why Pearls Remain a Timeless Choice', 'Different Types of Pearls', 'The 5 Factors That Determine Pearl Quality', 'Pearl and Vedic Astrology', 'How to Avoid Fake Pearls', 'Looking for a Pearl Dealer in California?'],
  },
  {
    path: '/buy-natural-certified-pearl-moti-gemstone-in-new-york',
    destination: '/knowledge/gem-qualities/pearl',
    city: 'New York',
    title: 'Buy Natural & Certified Pearl (Moti) Gemstone in New York',
    description: 'Buy natural and certified Pearl (Moti) gemstones in New York. Explore authentic pearls with certification, quality assurance, astrological significance, and lasting beauty.',
    h1: 'Buy Natural & Certified Pearl (Moti) Gemstone in New York',
    topics: ['Why is Pearl Popular?', 'Why Choose a Certified Pearl?', 'Pearl Healing and Spiritual Significance', 'Choosing the Right Pearl', 'Price and Quality', 'Conclusion'],
  },
  {
    path: '/buy-natural-certified-pearls-in-abu-dhabi-a-complete-buying-guide',
    destination: '/knowledge/gem-qualities/pearl',
    city: 'Abu Dhabi',
    title: 'Buy Natural & Certified Pearls in Abu Dhabi A Complete Buying Guide',
    description: 'Buy natural & certified pearls in Abu Dhabi with confidence. Learn how to identify genuine pearls, understand certification, pricing, Vedic astrology, and smart buying tips before purchasing.',
    h1: 'Buy Natural & Certified Pearls in Abu Dhabi A Complete Buying Guide',
    topics: ['How to Identify a Genuine Pearl', 'Why Acquire a Certified Pearl?', 'Pearl and Vedic Astrology', 'Mistakes to Keep in Mind', 'Where to Buy Pearl in Abu Dhabi?', 'What Affects Pearl Price?'],
  },
  {
    path: '/buy-natural-certified-red-coral-in-abu-dhabi-original-moonga-stone',
    destination: '/knowledge/gem-qualities/red-coral',
    city: 'Abu Dhabi',
    title: 'Buy Natural & Certified Red Coral in Abu Dhabi Original Moonga Stone',
    description: 'Buy natural & certified Red Coral (Moonga) in Abu Dhabi. Learn how to identify genuine coral, understand certification, pricing, quality factors, and Vedic astrology guidance before buying.',
    h1: 'Buy Natural & Certified Red Coral in Abu Dhabi Original Moonga Stone',
    topics: ['What Makes a Good Quality Red Coral?', 'Why Buy a Certified Red Coral?', 'Red Coral and Vedic Astrology', 'Common Mistakes Buyers Should Avoid', 'Where to Buy Red Coral in Abu Dhabi?', 'What Affects Red Coral Price?'],
  },
  {
    path: '/buy-natural-certified-red-coral-in-california-trusted-moonga-stone-dealer',
    destination: '/knowledge/gem-qualities/red-coral',
    city: 'California',
    title: 'Buy Natural & Certified Red Coral in California | Trusted Moonga Stone Dealer',
    description: 'Buy natural & certified Red Coral (Moonga) in California from a trusted gemstone dealer. Explore Italian & Japanese Red Coral, Vedic astrology guidance, certification, pricing, and expert buying tips.',
    h1: 'Buy Natural & Certified Red Coral in California | Trusted Moonga Stone Dealer & Buying Guide',
    topics: ['Why Red Coral Differs from Other Gemstones', 'Italian vs Japanese Red Coral', 'How to Choose a Genuine Red Coral', 'Red Coral and Vedic Astrology', 'Mistakes to Avoid When Buying Red Coral', 'Looking for a Red Coral Dealer in California?'],
  },
  {
    path: '/buy-natural-certified-red-coral-moonga-gemstone-in-new-york',
    destination: '/knowledge/gem-qualities/red-coral',
    city: 'New York',
    title: 'Buy Natural & Certified Red Coral (Moonga) Gemstone in New York',
    description: 'Buy natural and certified Red Coral (Moonga) gemstones in New York. Learn about Red Coral benefits, astrological significance, healing properties, certification, quality factors, and how to choose an authentic gemstone.',
    h1: 'Buy Natural & Certified Red Coral (Moonga) Gemstone in New York',
    topics: ['Why is Red Coral Popular?', 'Why Choose a Certified Red Coral?', 'Red Coral Healing and Spiritual Significance', 'Choosing the Right Red Coral', 'Price and Quality', 'Conclusion'],
  },
  {
    path: '/buy-natural-certified-ruby-in-abu-dhabi-a-smart-buyers-guide',
    destination: '/knowledge/gem-qualities/ruby',
    city: 'Abu Dhabi',
    title: 'Buy Natural & Certified Ruby in Abu Dhabi A Smart Buyer\'s Guide',
    description: 'Looking to buy a natural & certified Ruby in Abu Dhabi? Learn how to identify genuine Manik gemstones, understand certification, pricing, quality, and Vedic astrology before making your purchase.',
    h1: 'Buy Natural & Certified Rubies in Abu Dhabi A Smart Buyer\'s Guide',
    topics: ['What Should You Look for in a Ruby?', 'Why Buy a Certified Ruby?', 'Ruby and Traditional Vedic Astrology', 'Common Buying Mistakes', 'Where to Buy Ruby in Abu Dhabi?', 'What Affects Ruby Price?'],
  },
  {
    path: '/buy-natural-certified-ruby-in-california-trusted-manik-dealer',
    destination: '/knowledge/gem-qualities/ruby',
    city: 'California',
    title: 'Buy Natural & Certified Ruby in California | Trusted Manik Dealer',
    description: 'Buy natural & certified Ruby (Manik) in California from a trusted dealer. Explore ruby origins, certification, Vedic astrology guidance, buying tips, jewellery options, and expert support.',
    h1: 'Buy Natural & Certified Ruby in California | Trusted Manik Stone Dealer & Buying Guide',
    topics: ['Why Ruby Is One of the Most Valuable Gemstones', 'Best Ruby Origins You Should Know', 'How to Select a High-Quality Ruby', 'Ruby and Vedic Astrology', 'Common Mistakes to Avoid When Buying Ruby', 'Looking for a Trusted Ruby Dealer in California?'],
  },
  {
    path: '/buy-natural-certified-ruby-in-texas-genuine-manik-stone-dealer',
    destination: '/knowledge/gem-qualities/ruby',
    city: 'Texas',
    title: 'Buy Natural & Certified Ruby in Texas | Genuine Manik Stone Dealer',
    description: 'Buy natural & certified Ruby (Manik) in Texas from a trusted gemstone dealer. Explore genuine certified rubies for luxury jewellery and Vedic astrology with transparent certification.',
    h1: 'Buy Natural & Certified Ruby in Texas | Genuine Manik Stone Dealer',
    topics: ['What makes ruby one of the most valuable gemstones on Earth?', 'Things to Consider in Choosing Rubies to Buy', 'Why Certification Matters', 'Ruby in Vedic Astrology', 'Conclusion'],
  },
  {
    path: '/buy-natural-certified-ruby-manik-gemstone-in-new-york',
    destination: '/knowledge/gem-qualities/ruby',
    city: 'New York',
    title: 'Buy Natural & Certified Ruby (Manik) Gemstone in New York',
    description: 'Buy natural and certified Ruby (Manik) gemstone in New York. Learn about ruby benefits, Vedic astrology significance, healing properties, certification, quality factors, and how to choose an authentic ruby.',
    h1: 'Buy Natural & Certified Ruby (Manik) Gemstone in New York',
    topics: ['Why is Ruby Popular?', 'Why Choose a Certified Ruby?', 'Ruby Healing and Spiritual Significance', 'Choosing the Right Ruby', 'Price and Quality', 'Conclusion'],
  },
  {
    path: '/buy-natural-certified-rudraksha-in-abu-dhabi-genuine-rudraksha-beads',
    destination: '/knowledge/rudraksha-qualities',
    city: 'Abu Dhabi',
    title: 'Buy Natural & Certified Rudraksha in Abu Dhabi | Genuine Rudraksha Beads',
    description: 'Buy natural & certified Rudraksha in Abu Dhabi with confidence. Learn about Mukhi types, authenticity, certification, Vedic guidance, and tips for choosing genuine Rudraksha beads.',
    h1: 'Buy Natural & Certified Rudraksha in Abu Dhabi | Genuine Rudraksha Beads',
    topics: ['Why is Rudraksha Popular?', 'Main Types of Rudraksha', 'Reasons to Choose Certified Rudraksha', 'Rudraksha and Vedic Guidance', 'Where to Buy Rudraksha in Abu Dhabi?', 'Mistakes to Avoid'],
  },
  {
    path: '/buy-natural-certified-rudraksha-in-new-york-types-benefits-buying-guide',
    destination: '/knowledge/rudraksha-qualities',
    city: 'New York',
    title: 'Buy Natural & Certified Rudraksha in New York Types, Benefits & Buying Guide',
    description: 'Buy natural and certified Rudraksha in New York. Explore different Mukhi Rudraksha types, benefits, spiritual significance, authenticity tips, and expert buying guidance.',
    h1: 'Buy Natural & Certified Rudraksha in New York Types, Benefits & Buying Guide',
    topics: ['Why is Rudraksha Popular?', 'Why Choose a Certified Rudraksha?', 'Popular Types of Rudraksha', 'Rudraksha and Spiritual Significance', 'Choosing the Right Rudraksha', 'Price and Quality'],
  },
  {
    path: '/buy-natural-certified-rudraksha-in-sharjah-complete-buying-guide',
    destination: '/knowledge/rudraksha-qualities',
    city: 'Sharjah',
    title: 'Buy Natural & Certified Rudraksha in Sharjah – Complete Buying Guide',
    description: 'Discover how to buy natural & certified Rudraksha in Sharjah. Learn about Mukhi types, authenticity, horoscope analysis, buying tips, and how to identify genuine Rudraksha beads before purchasing.',
    h1: 'Buy Natural & Certified Rudraksha in Sharjah – Complete Buying Guide',
    topics: ['What is Rudraksha?', 'Main Types of Rudraksha', 'Why Horoscope Analysis Matters', 'How to Identify a Genuine Rudraksha', 'Beware of Fake Rudraksha', 'Conclusion'],
  },
  {
    path: '/buy-natural-certified-white-sapphire-gemstone-in-new-york',
    destination: '/knowledge/gem-qualities/white-sapphire',
    city: 'New York',
    title: 'Buy Natural & Certified White Sapphire Gemstone in New York | Authentic Shukra Ratna',
    description: 'Buy natural and certified White Sapphire gemstones in New York. Discover White Sapphire benefits, Venus (Shukra) significance, certification tips, quality factors, and buying guidance.',
    h1: 'Buy Natural & Certified White Sapphire Gemstone in New York',
    topics: ['Why is White Sapphire Popular?', 'Why Choose a Certified White Sapphire?', 'White Sapphire Healing and Spiritual Significance', 'Choosing the Right White Sapphire', 'Price and Quality', 'Conclusion'],
  },
  {
    path: '/buy-natural-certified-white-sapphire-in-abu-dhabi-a-complete-buying-guide',
    destination: '/knowledge/gem-qualities/white-sapphire',
    city: 'Abu Dhabi',
    title: 'Buy Natural & Certified White Sapphire in Abu Dhabi – A Complete Buying Guide',
    description: 'Buy natural & certified White Sapphire in Abu Dhabi. Learn how to identify genuine Safed Pukhraj, verify certification, understand pricing, quality and Vedic astrology.',
    h1: 'Buy Natural & Certified White Sapphire in Abu Dhabi – A Complete Buying Guide',
    topics: ['How to Identify a Genuine White Sapphire', 'Why Buy a Certified White Sapphire?', 'White Sapphire and Vedic Astrology', 'Mistakes that Purchasers Need to Avoid', 'Where to Buy White Sapphire in Abu Dhabi?', 'What Affects White Sapphire Price?'],
  },
  {
    path: '/buy-natural-certified-white-sapphire-in-birmingham-guide',
    destination: '/knowledge/gem-qualities/white-sapphire',
    city: 'Birmingham',
    title: 'Buy Natural & Certified White Sapphire in Birmingham Guide',
    description: 'Buy natural & certified White Sapphire in Birmingham. Learn how to identify genuine Safed Pukhraj, understand treatments, pricing, certification, and buying tips.',
    h1: 'Buy Natural & Certified White Sapphire in Birmingham | Trusted Lehsunia Dealer & Buying Guide',
    topics: ['Why White Sapphire is Growing in Popularity', 'How to Identify a Genuine White Sapphire', 'Natural vs Treated White Sapphire', 'White Sapphire and Vedic Astrology', 'Questions to Ask Before Buying', 'Looking for a white sapphire dealer in Birmingham?'],
  },
  {
    path: '/buy-natural-certified-white-sapphire-in-california',
    destination: '/knowledge/gem-qualities/white-sapphire',
    city: 'California',
    title: 'Buy Natural & Certified White Sapphire in California',
    description: 'Buy natural & certified White Sapphire in California from trusted dealers. Learn about quality, origins, certification, Vedic astrology, and buying tips.',
    h1: 'Buy Natural & Certified White Sapphire in California | Trusted White Sapphire Dealer & Buying Guide',
    topics: ['Why White Sapphire is Gaining Popularity in California', 'Best Origins of White Sapphire', 'How to Choose a Genuine White Sapphire', 'White Sapphire and Vedic Astrology', 'Common Buying Mistakes to Avoid', 'Caring for Your White Sapphire Jewellery'],
  },
  {
    path: '/buy-natural-certified-yellow-sapphire-in-abu-dhabi-pukhraj-buying-guide',
    destination: '/knowledge/gem-qualities/yellow-sapphire',
    city: 'Abu Dhabi',
    title: 'Buy Natural & Certified Yellow Sapphire in Abu Dhabi Pukhraj Buying Guide',
    description: 'Buy natural & certified Yellow Sapphire (Pukhraj) in Abu Dhabi. Learn how to identify genuine gemstones, understand certification, pricing, quality, and Vedic astrology guidance before purchasing.',
    h1: 'Buy Natural & Certified Yellow Sapphire in Abu Dhabi Pukhraj Buying Guide',
    topics: ['How to Identify a Genuine Yellow Sapphire', 'Why Certification is Important', 'Yellow Sapphire and Vedic Astrology', 'Common Mistakes to Avoid', 'What Affects the Price?', 'Where to Buy Yellow Sapphire in Abu Dhabi?'],
  },
  {
    path: '/buy-natural-certified-yellow-sapphire-in-california-pukhraj',
    destination: '/knowledge/gem-qualities/yellow-sapphire',
    city: 'California',
    title: 'Buy Natural & Certified Yellow Sapphire in California | Pukhraj',
    description: 'Buy natural & certified Yellow Sapphire (Pukhraj) in California from a trusted dealer. Explore Ceylon, Madagascar & Thailand origins with expert buying guidance.',
    h1: 'Buy Natural & Certified Yellow Sapphire in California | Trusted Pukhraj Dealer & Buying Guide',
    topics: ['Why Yellow Sapphire is Popular in California', 'Best Origins of Yellow Sapphire', 'Popular Yellow Sapphire Jewellery', 'Yellow Sapphire and Vedic Astrology', 'Common Mistakes to Avoid', 'Looking for a Yellow Sapphire Dealer in California?'],
  },
  {
    path: '/buy-natural-certified-yellow-sapphire-in-texas-genuine-pukhraj-stone-dealer',
    destination: '/knowledge/gem-qualities/yellow-sapphire',
    city: 'Texas',
    title: 'Buy Natural & Certified Yellow Sapphire in Texas | Genuine Pukhraj Stone Dealer',
    description: 'Buy natural & certified Yellow Sapphire (Pukhraj) in Texas from a trusted gemstone dealer. Explore sapphire quality, certification, origins, Vedic astrology, pricing factors, and expert buying guidance.',
    h1: 'Buy Natural & Certified Yellow Sapphire in Texas | Genuine Pukhraj Stone Dealer',
    topics: ['Why Yellow Sapphire Is the Preferable Option for Consumers?', 'Why a Certified Yellow Sapphire Matters', 'What Determines the Value of a Yellow Sapphire?', 'Yellow Sapphire from Sri Lanka or Madagascar', 'Yellow Sapphire in Luxury Jewellery', 'Steps for Verifying a Real Yellow Sapphire'],
  },
  {
    path: '/buy-natural-certified-yellow-sapphire-pukhraj-gemstone-in-new-york',
    destination: '/knowledge/gem-qualities/yellow-sapphire',
    city: 'New York',
    title: 'Buy Natural & Certified Yellow Sapphire (Pukhraj) Gemstone in New York',
    description: 'Buy natural and certified Yellow Sapphire (Pukhraj) gemstone in New York. Explore its astrological significance, benefits, healing properties, certification importance, quality factors, and tips for choosing an authentic yellow sapphire from trusted dealers.',
    h1: 'Buy Natural & Certified Yellow Sapphire (Pukhraj) Gemstone in New York',
    topics: ['Why is Yellow Sapphire Popular?', 'Why Choose a Certified Yellow Sapphire?', 'Yellow Sapphire Healing and Spiritual Significance', 'Choosing the Right Yellow Sapphire', 'Price and Quality', 'Conclusion'],
  },
  {
    path: '/buy-original-certified-rudraksha-in-birmingham-guide',
    destination: '/knowledge/rudraksha-qualities',
    city: 'Birmingham',
    title: 'Buy Original & Certified Rudraksha in Birmingham Guide',
    description: 'Buy original & certified Rudraksha in Birmingham. Learn about Mukhi types, authenticity, certification, pricing, Vedic significance, and smart buying tips.',
    h1: 'Buy Original & Certified Rudraksha in Birmingham | Complete Buying Guide',
    topics: ['Why Rudraksha is So Popular', 'Popular Types of Rudraksha', 'How to Identify Original Rudraksha', 'Rudraksha and Vedic Astrology', 'Looking for a Rudraksha Dealer in Birmingham?', 'Understanding Rudraksha Prices'],
  },
  {
    path: '/cats-eye-gemstone-in-malaysia-natural-certified-ketu-stone-for-protection-spiritual-growth',
    destination: '/knowledge/gem-qualities/catseye',
    city: 'Malaysia',
    title: 'Cat’s Eye Gemstone in Malaysia Natural Certified Ketu Stone for Protection & Spiritual Growth',
    description: 'Buy natural certified Cat’s Eye gemstone in Malaysia for protection, success, and spiritual growth. Learn astrological benefits, price factors, healing properties, and how to choose genuine Ketu stone.',
    h1: 'Cat\'s Eye Gemstone in Malaysia Natural Certified Stone for Protection, Success, and Spiritual Growth',
    topics: ['What is Cat\'s Eye Gemstone', 'Astrological Importance of Cat\'s Eye', 'Healing and Energy Benefits', 'How to Choose the Right Cat\'s Eye Gemstone', 'Cat\'s Eye Gemstone Price Factors', 'Who Should Wear Cat\'s Eye'],
  },
  {
    path: '/cats-eye-gemstone-in-philippines-natural-certified-stone-for-protection-and-success',
    destination: '/knowledge/gem-qualities/catseye',
    city: 'Philippines',
    title: 'Cat\'s Eye Gemstone in Philippines Natural Certified Stone for Protection and Success',
    description: 'Buy natural certified catseye with Vedic astrology guidance for Philippines. Authenticity, quality tips, and Pure Vedic Gems heritage since 1937.',
    h1: 'Cat\'s Eye Gemstone in Philippines Natural Certified Stone for Protection and Success',
    topics: ['What is Cat\'s Eye Gemstone', 'Astrological Importance of Cat\'s Eye', 'Healing and Energy Benefits', 'How to Choose the Right Cat\'s Eye Gemstone', 'Cat\'s Eye Gemstone Price Factors', 'Who Should Wear Cat\'s Eye'],
  },
  {
    path: '/cats-eye-stone-in-birmingham-genuine-certified-buying-guide',
    destination: '/knowledge/gem-qualities/catseye',
    city: 'Birmingham',
    title: 'Cat\'s Eye Stone in Birmingham | Genuine Certified Buying Guide',
    description: 'Buy natural certified catseye with Vedic astrology guidance for Birmingham. Authenticity, quality tips, and Pure Vedic Gems heritage since 1937.',
    h1: 'Cat\'s Eye Stone in Birmingham | How to Buy a Genuine Certified Gemstone',
    topics: ['What Makes Cat\'s Eye Unique?', 'How to Identify a Genuine Cat\'s Eye', 'Natural vs Treated Cat\'s Eye', 'Cat\'s Eye and Vedic Astrology', 'Questions to Ask Before Buying', 'Looking for a Cat\'s Eye Dealer in Birmingham?'],
  },
  {
    path: '/find-the-perfect-natural-ruby-in-birmingham-buyers-guide',
    destination: '/knowledge/gem-qualities/ruby',
    city: 'Birmingham',
    title: 'Find the Perfect Natural Ruby in Birmingham | Buyer\'s Guide',
    description: 'Looking to buy a natural ruby in Birmingham? Learn how to identify certified rubies, understand treatments, compare quality, and choose a trusted ruby dealer with this expert buying guide.',
    h1: 'Find the Perfect Natural Ruby in Birmingham | Buyer\'s Guide',
    topics: ['Why Ruby Continues to Be a Popular Choice', 'What Makes a High-Quality Ruby?', 'Natural vs Treated Ruby', 'Ruby and Vedic Astrology', 'Questions You Should Ask Before Buying', 'Looking for a ruby dealer in Birmingham?'],
  },
  {
    path: '/natural-certified-blue-sapphire-in-sharjah-complete-neelam-buying-guide',
    destination: '/knowledge/gem-qualities/blue-sapphire',
    city: 'Sharjah',
    title: 'Natural & Certified Blue Sapphire in Sharjah Complete Neelam Buying Guide',
    description: 'Looking to buy a natural and certified Blue Sapphire in Sharjah? Explore this complete guide covering Neelam benefits, certification, quality factors, pricing, and Vedic astrology recommendations.',
    h1: 'Natural & Certified Blue Sapphire in Sharjah Complete Buying Guide',
    topics: ['Why is Blue Sapphire Popular?', 'Why Choose a Certified Blue Sapphire?', 'Blue Sapphire Healing and Spiritual Significance', 'Choosing the Right Blue Sapphire', 'Price and Quality', 'Conclusion'],
  },
  {
    path: '/natural-certified-cats-eye-in-sharjah-complete-buying-guide',
    destination: '/knowledge/gem-qualities/catseye',
    city: 'Sharjah',
    title: 'Natural & Certified Cat\'s Eye in Sharjah – Complete Buying Guide',
    description: 'Learn how to buy natural & certified Cat',
    h1: 'Natural & Certified Cat\'s Eye in Sharjah – Complete Buying Guide',
    topics: ['What Makes Cat\'s Eye Unique?', 'Commonly Associated Benefits', 'Understanding Quality Before Buying', 'Why Horoscope Analysis Matters', 'Common Uses of Cat\'s Eye', 'Suggestions for Purchasing a Cat\'s Eye in Sharjah'],
  },
  {
    path: '/natural-certified-emerald-in-sharjah-complete-buying-guide',
    destination: '/knowledge/gem-qualities/emerald',
    city: 'Sharjah',
    title: 'Natural & Certified Emerald in Sharjah Complete Buying Guide',
    description: 'Learn how to buy a natural and certified Emerald (Panna) in Sharjah. Understand quality, certification, authenticity, pricing, horoscope analysis, and key buying tips before purchasing.',
    h1: 'Natural & Certified Emerald in Sharjah Complete Buying Guide',
    topics: ['Understanding Emerald', 'Commonly Associated Benefits', 'Know What to Look for Before Purchasing an Emerald', 'Why Horoscope Analysis Matters', 'Common Uses of Emerald', 'Buying Tips'],
  },
  {
    path: '/natural-certified-hessonite-in-sharjah-complete-buying-guide',
    destination: '/knowledge/gem-qualities/hessonite',
    city: 'Sharjah',
    title: 'Natural & Certified Hessonite in Sharjah Complete Buying Guide',
    description: 'Learn how to buy natural & certified Hessonite (Gomed) in Sharjah. Explore quality factors, certification, pricing, authenticity checks, and Vedic astrology considerations before purchase.',
    h1: 'Natural & Certified Hessonite in Sharjah Complete Buying Guide',
    topics: ['Understanding Hessonite', 'Commonly Associated Benefits', 'Understanding What to Look For Before Purchasing', 'Why Horoscope Analysis Matters', 'Common Uses of Hessonite', 'Buying Tips'],
  },
  {
    path: '/natural-certified-opal-in-sharjah-complete-buying-guide',
    destination: '/knowledge/gem-qualities/opal',
    city: 'Sharjah',
    title: 'Natural & Certified Opal in Sharjah Complete Buying Guide',
    description: 'Learn how to buy a natural and certified Opal in Sharjah. Discover quality factors, certification, authenticity, common uses, buying tips, and Vedic astrology guidance before purchasing.',
    h1: 'Natural & Certified Opal in Sharjah Complete Buying Guide',
    topics: ['Understanding Opal', 'Commonly Associated Benefits', 'Understanding Quality Before Buying', 'Why Horoscope Analysis Matters', 'Common Uses of Opal', 'Buying Tips'],
  },
  {
    path: '/natural-certified-pearl-in-sharjah-complete-buying-guide',
    destination: '/knowledge/gem-qualities/pearl',
    city: 'Sharjah',
    title: 'Buy Natural Pearl in Sharjah Pearl Quality & Certification Guide',
    description: 'Explore everything you need to know before buying a pearl in Sharjah, including authenticity, certification, quality factors, and common uses.',
    h1: 'Natural & Certified Pearl in Sharjah Complete Buying Guide',
    topics: ['Understanding Pearl', 'Commonly Associated Benefits', 'Understanding Quality Before Buying', 'Why Horoscope Analysis Matters', 'Common Uses of Pearl', 'Buying Tips'],
  },
  {
    path: '/natural-certified-red-coral-in-birmingham-buying-guide',
    destination: '/knowledge/gem-qualities/red-coral',
    city: 'Birmingham',
    title: 'Natural & Certified Red Coral in Birmingham | Buying Guide',
    description: 'Learn how to buy natural & certified Red Coral (Moonga) in Birmingham. Discover quality checks, certification, pricing, Vedic astrology, and expert buying tips.',
    h1: 'Buy Natural & Certified Red Coral in Birmingham | Complete Buying Guide',
    topics: ['What Makes Red Coral Unique from Other Gem Stones', 'How to Identify a Genuine Red Coral', 'Natural vs Dyed Red Coral', 'Red Coral and Vedic Astrology', 'Questions to Ask Before Buying Red Coral', 'Looking for a Red Coral Dealer in Birmingham?'],
  },
  {
    path: '/natural-certified-red-coral-in-sharjah-complete-moonga-buying-guide',
    destination: '/knowledge/gem-qualities/red-coral',
    city: 'Sharjah',
    title: 'Natural & Certified Red Coral in Sharjah Complete Moonga Buying Guide',
    description: 'Discover how to buy natural and certified Red Coral (Moonga) in Sharjah. Learn about quality, authenticity, certification, pricing factors, benefits, and expert buying tips.',
    h1: 'Natural & Certified Red Coral in Sharjah Complete Buying Guide',
    topics: ['Understanding Red Coral', 'Commonly Associated Benefits', 'Understanding Quality Before Buying', 'Why Horoscope Analysis Matters', 'Common Uses of Red Coral', 'Buying Tips'],
  },
  {
    path: '/natural-certified-ruby-in-sharjah-complete-ruby-buying-guide',
    destination: '/knowledge/gem-qualities/ruby',
    city: 'Sharjah',
    title: 'Natural & Certified Ruby in Sharjah Complete Ruby Buying Guide',
    description: 'Learn how to buy a natural and certified Ruby in Sharjah. Understand Ruby quality, certification, benefits, pricing factors, and key tips for choosing an authentic gemstone.',
    h1: 'Natural & Certified Ruby in Sharjah A Complete Guide for Buyers',
    topics: ['Understanding Ruby', 'Commonly Associated Benefits', 'Quality of Ruby Prior to Purchase', 'Why Horoscope Analysis Matters', 'Common Uses of Ruby', 'Advice on how to Buy a Ruby in Sharjah'],
  },
  {
    path: '/natural-certified-white-sapphire-in-sharjah-complete-buying-guide',
    destination: '/knowledge/gem-qualities/white-sapphire',
    city: 'Sharjah',
    title: 'Natural & Certified White Sapphire in Sharjah – Complete Buying Guide',
    description: 'Learn how to buy a natural and certified White Sapphire (Safed Pukhraj) in Sharjah. Discover quality factors, certification, benefits, buying tips, horoscope guidance, and price information',
    h1: 'Natural & Certified White Sapphire in Sharjah – Complete Buying Guide',
    topics: ['What Makes White Sapphire Special?', 'Commonly Associated Benefits', 'How to Select the Best Quality White Sapphire Before the Purchase', 'Why Horoscope Analysis Matters', 'Common Uses of White Sapphire', 'Buying Tips'],
  },
  {
    path: '/natural-certified-yellow-sapphire-in-birmingham-expert-buying-guide',
    destination: '/knowledge/gem-qualities/yellow-sapphire',
    city: 'Birmingham',
    title: 'Natural & Certified Yellow Sapphire in Birmingham- Expert Buying Guide',
    description: 'Looking to buy a natural yellow sapphire in Birmingham? Learn how to verify certification, compare quality, understand treatments, pricing, and choose a trusted Pukhraj dealer with this expert buying guide.',
    h1: 'Natural & Certified Yellow Sapphire in Birmingham- Expert Buying Guide',
    topics: ['Why Buyers Choose Yellow Sapphire', 'How to Check the Quality of a Yellow Sapphire', 'Natural vs Heated Yellow Sapphire', 'Yellow Sapphire and Vedic Astrology', 'Questions Every Buyer Should Ask', 'Looking for a Yellow Sapphire Dealer in Birmingham?'],
  },
  {
    path: '/natural-certified-yellow-sapphire-in-sharjah-complete-buying-guide',
    destination: '/knowledge/gem-qualities/yellow-sapphire',
    city: 'Sharjah',
    title: 'Natural & Certified Yellow Sapphire in Sharjah Complete Buying Guide',
    description: 'Learn how to buy a natural and certified yellow sapphire in Sharjah. Discover quality factors, certification importance, horoscope considerations, buying tips, and pricing insights for informed gemstone purchases.',
    h1: 'Natural & Certified Yellow Sapphire in Sharjah Complete Buying Guide',
    topics: ['Understanding Yellow Sapphire', 'Commonly Associated Benefits', 'Key Factors to Consider', 'Why Horoscope Analysis Matters', 'Common Uses of Yellow Sapphire', 'Buying Tips'],
  },
  {
    path: '/opal-gemstone-in-malaysia-natural-certified-stone-for-love-healing-and-peace',
    destination: '/knowledge/gem-qualities/opal',
    city: 'Malaysia',
    title: 'Opal Gemstone in Malaysia Natural Certified Stone for Love, Healing & Peace',
    description: 'Buy natural certified Opal gemstone in Malaysia for love, emotional healing, creativity, and peace. Discover astrological benefits, price factors, care tips, and how to choose genuine opals.',
    h1: 'Opal Gemstone in Malaysia Natural Certified Stone for Love Healing and Peace',
    topics: ['What is the Opal Gemstone', 'Why Choose a Certified Opal Gemstone', 'Astrological Importance of Opal', 'Healing and Energy Benefits', 'How to Choose the Right Opal Gemstone', 'Opal Gemstone Price Factors'],
  },
  {
    path: '/the-ultimate-guide-to-buying-natural-blue-sapphire-in-birmingham',
    destination: '/knowledge/gem-qualities/blue-sapphire',
    city: 'Birmingham',
    title: 'The Ultimate Guide to Buying Natural Blue Sapphire in Birmingham',
    description: 'Learn how to buy a natural Blue Sapphire (Neelam) in Birmingham. Discover certification, treatment, pricing, Vedic astrology guidance, and expert tips for choosing an authentic sapphire.',
    h1: 'The Ultimate Guide to Buying Natural Blue Sapphire in Birmingham',
    topics: ['Why Birmingham is a Popular Destination for Blue Sapphire Buyers', 'Natural vs Treated Blue Sapphire', 'How to Verify a Genuine Blue Sapphire', 'Blue Sapphire and Vedic Astrology', 'Questions to Ask Before Buying', 'Looking for a Blue Sapphire Dealer in Birmingham?'],
  },
];

export const GEO_BUY_KEYWORDS_BY_DEST: Record<string, string[]> = {
  "/knowledge/rudraksha-qualities": [
    "buy california",
    "buy authentic & certified rudraksha in california",
    "trusted rudraksha dealer",
    "buy abu dhabi",
    "buy natural & certified rudraksha in abu dhabi",
    "genuine rudraksha beads",
    "buy new york",
    "buy natural & certified rudraksha in new york types",
    "benefits & buying guide",
    "buy sharjah",
    "buy natural & certified rudraksha in sharjah",
    "complete buying guide",
    "buy birmingham",
    "buy original & certified rudraksha in birmingham guide",
    "natural certified rudraksha qualities",
    "rudraksha qualities buying guide"
  ],
  "/knowledge/gem-qualities/blue-sapphire": [
    "buy new york",
    "buy natural & certified blue sapphire gemstone in new york",
    "buy abu dhabi",
    "buy california",
    "buy natural & certified blue sapphire in california",
    "trusted neelam dealer",
    "buy texas",
    "buy natural & certified blue sapphire in texas",
    "trusted neelam stone dealer",
    "buy sharjah",
    "buy birmingham",
    "natural certified blue sapphire",
    "blue sapphire buying guide"
  ],
  "/knowledge/gem-qualities/catseye": [
    "buy abu dhabi",
    "buy natural & certified cat's eye in abu dhabi",
    "a complete buying guide",
    "buy california",
    "buy natural & certified cat's eye in california",
    "premium lehsunia dealer",
    "buy new york",
    "buy malaysia",
    "buy philippines",
    "buy birmingham",
    "cat's eye stone in birmingham",
    "genuine certified buying guide",
    "buy sharjah",
    "natural & certified cat's eye in sharjah",
    "complete buying guide",
    "natural certified catseye",
    "catseye buying guide"
  ],
  "/knowledge/gem-qualities/emerald": [
    "buy california",
    "buy natural & certified emerald in california",
    "trusted panna stone dealer",
    "buy new york",
    "buy abu dhabi",
    "buy natural & certified emeralds in abu dhabi",
    "a complete buying guide",
    "buy birmingham",
    "buy natural & certified emeralds in birmingham",
    "expert guide",
    "buy sharjah",
    "natural certified emerald",
    "emerald buying guide"
  ],
  "/knowledge/gem-qualities/hessonite": [
    "buy new york",
    "uses & buying guide",
    "buy california",
    "buy natural & certified hessonite (gomed) in california",
    "trusted dealer",
    "buy abu dhabi",
    "buy natural & certified hessonite in abu dhabi",
    "a complete buying guide",
    "buy birmingham",
    "buy natural & certified hessonite in birmingham",
    "buy sharjah",
    "natural certified hessonite",
    "hessonite buying guide"
  ],
  "/knowledge/gem-qualities/opal": [
    "buy new york",
    "buy abu dhabi",
    "buy natural & certified opal in abu dhabi",
    "original opal buying guide",
    "buy birmingham",
    "buy natural & certified opal in birmingham",
    "buying guide",
    "buy california",
    "buy natural & certified opal in california",
    "trusted opal dealer",
    "buy sharjah",
    "natural & certified opal in sharjah complete buying guide",
    "buy malaysia",
    "opal gemstone in malaysia natural certified stone for love",
    "healing & peace",
    "natural certified opal",
    "opal buying guide"
  ],
  "/knowledge/gem-qualities/pearl": [
    "buy birmingham",
    "buy natural & certified pearl in birmingham",
    "buying guide",
    "buy california",
    "buy natural & certified pearl in california",
    "trusted pearl dealer",
    "buy new york",
    "buy natural & certified pearl (moti) gemstone in new york",
    "buy abu dhabi",
    "buy sharjah",
    "natural certified pearl",
    "pearl buying guide"
  ],
  "/knowledge/gem-qualities/red-coral": [
    "buy abu dhabi",
    "buy california",
    "buy natural & certified red coral in california",
    "trusted moonga stone dealer",
    "buy new york",
    "buy birmingham",
    "natural & certified red coral in birmingham",
    "buying guide",
    "buy sharjah",
    "natural certified red coral",
    "red coral buying guide"
  ],
  "/knowledge/gem-qualities/ruby": [
    "buy abu dhabi",
    "buy california",
    "buy natural & certified ruby in california",
    "trusted manik dealer",
    "buy texas",
    "buy natural & certified ruby in texas",
    "genuine manik stone dealer",
    "buy new york",
    "buy natural & certified ruby (manik) gemstone in new york",
    "buy birmingham",
    "find the perfect natural ruby in birmingham",
    "buyer's guide",
    "buy sharjah",
    "natural certified ruby",
    "ruby buying guide"
  ],
  "/knowledge/gem-qualities/white-sapphire": [
    "buy new york",
    "buy natural & certified white sapphire gemstone in new york",
    "authentic shukra ratna",
    "buy abu dhabi",
    "buy natural & certified white sapphire in abu dhabi",
    "a complete buying guide",
    "buy birmingham",
    "buy natural & certified white sapphire in birmingham guide",
    "buy california",
    "buy natural & certified white sapphire in california",
    "buy sharjah",
    "natural & certified white sapphire in sharjah",
    "complete buying guide",
    "natural certified white sapphire",
    "white sapphire buying guide"
  ],
  "/knowledge/gem-qualities/yellow-sapphire": [
    "buy abu dhabi",
    "buy california",
    "buy natural & certified yellow sapphire in california",
    "buy texas",
    "buy natural & certified yellow sapphire in texas",
    "genuine pukhraj stone dealer",
    "buy new york",
    "buy birmingham",
    "natural & certified yellow sapphire in birmingham",
    "expert buying guide",
    "buy sharjah",
    "natural certified yellow sapphire",
    "yellow sapphire buying guide"
  ]
};

export function geoBuySourcesForDest(destination: string): GeoBuySource[] {
  return GEO_BUY_SOURCES.filter((s) => s.destination === destination);
}

export function geoBuyCityList(destination: string, limit = 6): string[] {
  return [...new Set(geoBuySourcesForDest(destination).map((s) => s.city))].slice(0, limit);
}

export function geoBuyShipCopy(label: string, cities: string[]): string | null {
  if (cities.length === 0) return null;
  const listed = [...cities];
  const last = listed.pop();
  const places = listed.length ? `${listed.join(', ')} and ${last}` : last;
  return `Certified ${label} ships from our Delhi workshop to buyers in ${places}, with insured international delivery. Suitability still depends on the stone and, for astrological wear, a chart review.`;
}

/** Malaysia buy-guides wrongly pointed at /consultation; quality hubs are the commercial canonical. */
export const MALAYSIA_GEM_REDIRECTS: Array<[string, string]> = [
  ['/natural-certified-blue-sapphire-gemstone-in-malaysia-benefits-astrology-buying-guide', '/knowledge/gem-qualities/blue-sapphire'],
  ['/natural-certified-emerald-gemstone-in-malaysia-benefits-astrology-buying-guide', '/knowledge/gem-qualities/emerald'],
  ['/natural-certified-hessonite-gemstone-in-malaysia-benefits-astrology-buying-guide', '/knowledge/gem-qualities/hessonite'],
  ['/natural-certified-pearl-gemstone-in-malaysia-benefits-astrology-buying-guide', '/knowledge/gem-qualities/pearl'],
  ['/natural-certified-white-sapphire-gemstone-in-malaysia-benefits-astrology-buying-guide', '/knowledge/gem-qualities/white-sapphire'],
  ['/natural-yellow-sapphire-gemstone-in-malaysia-benefits-astrology-buying-guide', '/knowledge/gem-qualities/yellow-sapphire'],
  ['/red-coral-gemstone-in-malaysia-benefits-price-astrology-and-buying-guide', '/knowledge/gem-qualities/red-coral'],
  ['/ruby-gemstone-in-malaysia-natural-certified-astrological-stone-for-confidence-success-and-wealth-growth', '/knowledge/gem-qualities/ruby'],
];

export function geoBuyInternalJsonLd(
  destination: string,
  absoluteUrl: (path?: string) => string,
  pageName: string,
  pageDescription: string,
) {
  const sources = geoBuySourcesForDest(destination);
  if (sources.length === 0) return [];
  const url = absoluteUrl(destination);
  const keywords = GEO_BUY_KEYWORDS_BY_DEST[destination] || [];
  const abstract = sources
    .map((s) => `${s.title}. ${s.description} City: ${s.city}. Topics: ${s.topics.join('; ')}.`)
    .join(' ');

  return [
    {
      '@context': 'https://schema.org',
      '@type': 'WebPage',
      '@id': `${url}#geo-buy-webpage`,
      url,
      name: pageName,
      description: pageDescription,
      keywords: keywords.join(', '),
      inLanguage: ['en', 'hi'],
      about: sources.map((s) => ({ '@type': 'Thing', name: s.h1 || s.title })),
      audience: {
        '@type': 'Audience',
        audienceType: `Buyers in ${[...new Set(sources.map((s) => s.city))].join(', ')}`,
      },
      abstract,
    },
    {
      '@context': 'https://schema.org',
      '@type': 'ItemList',
      name: 'Legacy regional buy guides consolidated on this page',
      itemListElement: sources.map((s, i) => ({
        '@type': 'ListItem',
        position: i + 1,
        name: s.title,
        description: s.description,
        url,
      })),
    },
  ];
}
