export const NOTIFICATION_TEMPLATE_LIBRARY = [
  {
    key: 'order_confirmation',
    channel: 'email',
    label: 'Order confirmation',
    trigger: 'Payment verified',
    consent: 'Transactional',
    retryable: true,
  },
  {
    key: 'admin_order_alert',
    channel: 'email',
    label: 'Admin order alert',
    trigger: 'New order created or verified',
    consent: 'Internal operations',
    retryable: true,
  },
  {
    key: 'tracking_update',
    channel: 'email_whatsapp',
    label: 'Tracking update',
    trigger: 'Fulfillment status changes',
    consent: 'Transactional',
    retryable: true,
  },
  {
    key: 'review_request',
    channel: 'email_whatsapp',
    label: 'Delivered review request',
    trigger: 'Order delivered + cooling period',
    consent: 'Review request enabled',
    retryable: true,
  },
  {
    key: 'consultation_confirmation',
    channel: 'email_whatsapp',
    label: 'Consultation confirmation',
    trigger: 'Consultation booked or confirmed',
    consent: 'Transactional',
    retryable: true,
  },
  {
    key: 'abandoned_cart',
    channel: 'email',
    label: 'Abandoned cart',
    trigger: 'Known email with inactive cart',
    consent: 'Marketing consent required',
    retryable: true,
  },
  {
    key: 'wearing_guide',
    channel: 'email',
    label: 'Wearing guide',
    trigger: 'Post-purchase care journey',
    consent: 'Guides enabled',
    retryable: true,
  },
  {
    key: 'nps_reengagement',
    channel: 'email_whatsapp',
    label: 'NPS and re-engagement',
    trigger: 'Post-delivery Day 30+',
    consent: 'Marketing consent required',
    retryable: true,
  },
] as const;