/** Optimized PNG cards — generated by scripts/optimize-rudraksha-category-images.mjs */
export const RUDRAKSHA_CARDS_BASE = '/home/rudraksha-cards';

const card = (slug: string) => `${RUDRAKSHA_CARDS_BASE}/${slug}.png`;

export const RUDRAKSHA_MUKHI_IMAGE_BY_SLUG: Record<string, string> = {
  '1-mukhi': card('1-mukhi'),
  '2-mukhi': card('2-mukhi'),
  '3-mukhi': card('3-mukhi'),
  '4-mukhi': card('4-mukhi'),
  '5-mukhi': card('5-mukhi'),
  '6-mukhi': card('6-mukhi'),
  '7-mukhi': card('7-mukhi'),
  '8-mukhi': card('8-mukhi'),
  '9-mukhi': card('9-mukhi'),
  '10-mukhi': card('10-mukhi'),
  '11-mukhi': card('11-mukhi'),
  '12-mukhi': card('12-mukhi'),
  '13-mukhi': card('13-mukhi'),
  '14-mukhi': card('14-mukhi'),
  '15-mukhi': card('15-mukhi'),
  '16-mukhi': card('16-mukhi'),
  '17-mukhi': card('17-mukhi'),
  '18-mukhi': card('18-mukhi'),
  '19-mukhi': card('19-mukhi'),
  '20-mukhi': card('20-mukhi'),
  '21-mukhi': card('21-mukhi'),
};

export const RUDRAKSHA_SPECIAL_IMAGE_BY_SLUG: Record<string, string> = {
  'gauri-shankar': card('gauri-shankar'),
  'ganesh-rudraksha': card('ganesh-rudraksha'),
  'nir-mukhi': card('nir-mukhi'),
  'garbh-gauri': card('garbh-gauri'),
  'sawar-rudraksha': card('sawar-rudraksha'),
};

export const RUDRAKSHA_FEATURE_IMAGES = {
  collection: `${RUDRAKSHA_CARDS_BASE}/finest-quality-collection.png`,
  malas: `${RUDRAKSHA_CARDS_BASE}/exclusive-malas.png`,
  jewellery: `${RUDRAKSHA_CARDS_BASE}/customised-jewellery.png`,
} as const;

export function rudrakshaMukhiImage(slug: string): string | null {
  return RUDRAKSHA_MUKHI_IMAGE_BY_SLUG[slug] ?? RUDRAKSHA_SPECIAL_IMAGE_BY_SLUG[slug] ?? null;
}

export function rudrakshaMukhiImageByNumber(mukhi: number): string | null {
  return rudrakshaMukhiImage(`${mukhi}-mukhi`);
}

export function resolveRudrakshaNavImage(slug: string, image?: string | null): string | null {
  if (image) return image;
  return rudrakshaMukhiImage(slug);
}

export { resolveCategoryNavImage, collectGemstoneNavImageUrls } from '@/lib/constants/category-nav-images';
