/**
 * Worker entry (wrangler `main`) wrapping the OpenNext handler.
 *
 * 1. Client IP / geo: the app reads `x-forwarded-for` (rate limits) and `x-vercel-ip-*` (geo),
 *    which Vercel used to set. Here they are overwritten from Cloudflare's own data on every
 *    request, so clients can't spoof them.
 * 2. Cron: daily product-trash purge (triggers in wrangler.jsonc), called in-process.
 */
// @ts-expect-error generated by `opennextjs-cloudflare build`
import openNext from '../.open-next/worker.js';
// @ts-expect-error generated by `opennextjs-cloudflare build`
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from '../.open-next/worker.js';

type Env = Record<string, unknown> & { CRON_SECRET?: string; NEXT_PUBLIC_SITE_URL?: string };
type Ctx = { waitUntil(promise: Promise<unknown>): void };
type Geo = { city?: string; country?: string; regionCode?: string; latitude?: string; longitude?: string };

const handler = openNext as { fetch(req: Request, env: Env, ctx: Ctx): Promise<Response> };

export function withClientHeaders(request: Request): Request {
  const headers = new Headers(request.headers);
  for (const key of [...headers.keys()]) {
    if (key.startsWith('x-vercel-ip-') || key === 'x-forwarded-for' || key === 'x-real-ip') {
      headers.delete(key);
    }
  }
  const ip = request.headers.get('cf-connecting-ip');
  if (ip) {
    headers.set('x-forwarded-for', ip);
    headers.set('x-real-ip', ip);
  }
  const cf = (request as Request & { cf?: Geo }).cf;
  const geo: [string, string | undefined][] = [
    ['x-vercel-ip-country', cf?.country ?? request.headers.get('cf-ipcountry') ?? undefined],
    ['x-vercel-ip-country-region', cf?.regionCode],
    // Vercel URI-encodes the city; readers decodeURIComponent it.
    ['x-vercel-ip-city', cf?.city ? encodeURIComponent(cf.city) : undefined],
    ['x-vercel-ip-latitude', cf?.latitude],
    ['x-vercel-ip-longitude', cf?.longitude],
  ];
  for (const [key, value] of geo) if (value && value !== 'XX') headers.set(key, value);
  return new Request(request, { headers });
}

const worker = {
  fetch(request: Request, env: Env, ctx: Ctx) {
    return handler.fetch(withClientHeaders(request), env, ctx);
  },

  async scheduled(_controller: unknown, env: Env, ctx: Ctx) {
    const origin = (env.NEXT_PUBLIC_SITE_URL || 'https://www.purevedicgems.com').replace(/\/$/, '');
    const req = new Request(`${origin}/api/cron/purge-product-trash`, {
      headers: { authorization: `Bearer ${env.CRON_SECRET ?? ''}` },
    });
    const res = await handler.fetch(req, env, ctx);
    if (!res.ok) {
      throw new Error(`purge-product-trash failed: ${res.status} ${await res.text().catch(() => '')}`);
    }
  },
};

export default worker;
