/**
 * Worker entry (wrangler `main`) wrapping the OpenNext handler.
 *
 * 1. Client IP / geo: the app reads `x-forwarded-for` (rate limits) and `x-vercel-ip-*` (geo),
 *    which Vercel used to set. Here they are overwritten from Cloudflare's own data on every
 *    request, so clients can't spoof them.
 * 2. Cron: daily product-trash purge (triggers in wrangler.jsonc), called in-process.
 * 3. Edge cache for `public, s-maxage` responses and ISR pages (see edge-cache.ts).
 * 4. Cache warm-up of the busiest pages every 5 minutes, so real visitors rarely find caches empty.
 */
import { edgeCacheCopy, isEdgeCacheableRequest } from './edge-cache';

const WARM_CRON = '*/5 * * * *';
// ponytail: fixed list of top pages. Subcategory pages left out: 60s edge TTL, re-rendering them every
// 5 min would cost more CPU than it saves.
const WARM_PATHS = [
  '/',
  '/gemstones',
  '/gemstones/navaratna',
  '/gemstones/upratna',
  '/rudraksha',
  '/blog',
  '/about',
  '/contact',
  '/knowledge',
  '/consultation',
];
// @ts-expect-error generated by `opennextjs-cloudflare build`
import openNext from '../.open-next/worker.js';
// @ts-expect-error generated by `opennextjs-cloudflare build`
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from '../.open-next/worker.js';

type Env = Record<string, unknown> & {
  CRON_SECRET?: string;
  NEXT_PUBLIC_SITE_URL?: string;
  WORKER_SELF_REFERENCE?: { fetch(request: Request): Promise<Response> };
};
type Ctx = { waitUntil(promise: Promise<unknown>): void };
type Geo = { city?: string; country?: string; regionCode?: string; latitude?: string; longitude?: string };

const handler = openNext as { fetch(req: Request, env: Env, ctx: Ctx): Promise<Response> };

export function withClientHeaders(request: Request): Request {
  const headers = new Headers(request.headers);
  // Self-binding requests (warm cron, DO revalidation) have no Host; OpenNext queues ISR revalidation for headers.host.
  if (!headers.has('host')) headers.set('host', new URL(request.url).host);
  for (const key of [...headers.keys()]) {
    if (key.startsWith('x-vercel-ip-') || key === 'x-forwarded-for' || key === 'x-real-ip') {
      headers.delete(key);
    }
  }
  const ip = request.headers.get('cf-connecting-ip');
  if (ip) {
    headers.set('x-forwarded-for', ip);
    headers.set('x-real-ip', ip);
  }
  const cf = (request as Request & { cf?: Geo }).cf;
  const geo: [string, string | undefined][] = [
    ['x-vercel-ip-country', cf?.country ?? request.headers.get('cf-ipcountry') ?? undefined],
    ['x-vercel-ip-country-region', cf?.regionCode],
    // Vercel URI-encodes the city; readers decodeURIComponent it.
    ['x-vercel-ip-city', cf?.city ? encodeURIComponent(cf.city) : undefined],
    ['x-vercel-ip-latitude', cf?.latitude],
    ['x-vercel-ip-longitude', cf?.longitude],
  ];
  for (const [key, value] of geo) if (value && value !== 'XX') headers.set(key, value);
  return new Request(request, { headers });
}

const worker = {
  async fetch(request: Request, env: Env, ctx: Ctx) {
    if (!isEdgeCacheableRequest(request)) return handler.fetch(withClientHeaders(request), env, ctx);
    const cache = (caches as unknown as { default: Cache }).default;
    const hit = await cache.match(request.url);
    if (hit) return hit;
    const response = await handler.fetch(withClientHeaders(request), env, ctx);
    const copy = edgeCacheCopy(response);
    if (copy) ctx.waitUntil(cache.put(request.url, copy));
    return response;
  },

  async scheduled(controller: { cron: string }, env: Env, ctx: Ctx) {
    const origin = (env.NEXT_PUBLIC_SITE_URL || 'https://www.purevedicgems.com').replace(/\/$/, '');
    if (controller.cron === WARM_CRON) {
      // Through the service binding, not fetch(origin): a route Worker fetching its own zone would hit Vercel.
      const self = env.WORKER_SELF_REFERENCE;
      if (self) await Promise.allSettled(WARM_PATHS.map((p) => self.fetch(new Request(origin + p)).then((r) => r.arrayBuffer())));
      return;
    }
    const req = new Request(`${origin}/api/cron/purge-product-trash`, {
      headers: { authorization: `Bearer ${env.CRON_SECRET ?? ''}` },
    });
    const res = await handler.fetch(req, env, ctx);
    if (!res.ok) {
      throw new Error(`purge-product-trash failed: ${res.status} ${await res.text().catch(() => '')}`);
    }
  },
};

export default worker;
