export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

type ProductTypeValue =
  | 'simple'
  | 'variation'
  | 'gemstone'
  | 'rudraksha'
  | 'jewelry'
  | 'idol'
  | 'mala'
  | 'service'
  | 'external'
  | 'grouped'
  | 'downloadable';

type PriceModeValue = 'fixed' | 'per_carat' | 'on_demand' | 'quote_required' | 'free';
type StockStatusValue = 'in_stock' | 'out_of_stock' | 'on_backorder';
type AvailabilityStatusValue = 'in_stock' | 'out_of_stock' | 'sold' | 'reserved' | 'on_demand' | 'archived';
type CertificateStatusValue = 'not_required' | 'available' | 'included' | 'optional' | 'requested' | 'pending' | 'verified';
type ReturnEligibilityValue = 'standard' | 'loose_gemstone' | 'custom_jewellery' | 'service' | 'non_returnable' | 'manual_review';

export interface Database {
  public: {
    Tables: {
      products: {
        Row: {
          id: string;
          sku: string;
          name: string;
          slug: string;
          category: string;
          sub_category: string | null;
          product_type: ProductTypeValue;
          catalog_family: string | null;
          tag_number: string | null;
          import_warnings: Json;
          legacy_woo_id: number | null;
          legacy_permalink: string | null;
          legacy_status: string | null;
          legacy_catalog_visibility: string | null;
          legacy_type: string | null;
          legacy_data: Json;
          legacy_import_warnings: Json;
          price: number;
          price_per_carat: number | null;
          compare_price: number | null;
          currency: string;
          price_mode: PriceModeValue;
          base_currency: string;
          price_rule_notes: string | null;
          tax_status: string | null;
          tax_class: string | null;
          hsn_code: string | null;
          gst_rate: number | null;
          gst_exemption_reason: string | null;
          tax_inclusive: boolean;
          carat_weight: number | null;
          ratti_weight: number | null;
          origin: string | null;
          shape: string | null;
          treatment: string;
          color_grade: string | null;
          clarity: string | null;
          certification: string | null;
          quality_label: string | null;
          gender: string | null;
          metal_purity: string | null;
          setting_type: string | null;
          chain_type: string | null;
          bead_size_mm: number | null;
          bead_weight: number | null;
          rudraksha_origin: string | null;
          certificate_number: string | null;
          certificate_lab: string | null;
          certificate_status: CertificateStatusValue;
          certificate_issue_date: string | null;
          planet: string | null;
          vedic_name: string | null;
          hindi_name: string | null;
          chakra: string | null;
          rashi: string | null;
          finger: string | null;
          wearing_day: string | null;
          wearing_metal: string | null;
          mukhi_count: number | null;
          xray_certified: boolean;
          xray_certificate_number: string | null;
          ruling_deity: string | null;
          deity: string | null;
          rudraksha_type: string | null;
          energization_eligible: boolean;
          jewellery_type: string | null;
          base_metal: string | null;
          metal_weight_grams: number | null;
          size_label: string | null;
          ring_size: string | null;
          design_code: string | null;
          making_charge: number | null;
          ready_stock: boolean;
          return_eligibility: ReturnEligibilityValue;
          return_window_days: number;
          legal_disclosure_text: string | null;
          treatment_disclosure: string | null;
          care_instructions: string | null;
          high_value_review_required: boolean;
          composition: string | null;
          dimensions_mm: Json | null;
          short_desc: string | null;
          description: string | null;
          vedic_significance: string | null;
          mantra: string | null;
          benefits: Json;
          wearing_guide: string | null;
          expert_note: string | null;
          expert_id: string | null;
          images: Json;
          certificate_url: string | null;
          certificate_file_url: string | null;
          certificate_display_enabled: boolean;
          video_url: string | null;
          thumbnail_url: string | null;
          availability_status: AvailabilityStatusValue;
          stock_status: StockStatusValue;
          sold_individually: boolean;
          backorders_allowed: boolean;
          manual_reserve_enabled: boolean;
          reserved_quantity: number;
          reserved_until: string | null;
          reserved_by_customer_id: string | null;
          reserved_by_admin_id: string | null;
          reservation_note: string | null;
          in_stock: boolean;
          stock_quantity: number;
          low_stock_threshold: number;
          featured: boolean;
          is_directors_pick: boolean;
          configurator_enabled: boolean;
          is_active: boolean;
          display_order: number;
          meta_title: string | null;
          meta_description: string | null;
          seo_keywords: string[];
          canonical_category_slug: string | null;
          last_import_batch_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          sku: string;
          name: string;
          slug: string;
          category: string;
          sub_category?: string | null;
          product_type?: ProductTypeValue;
          catalog_family?: string | null;
          tag_number?: string | null;
          import_warnings?: Json;
          legacy_woo_id?: number | null;
          legacy_permalink?: string | null;
          legacy_status?: string | null;
          legacy_catalog_visibility?: string | null;
          legacy_type?: string | null;
          legacy_data?: Json;
          legacy_import_warnings?: Json;
          price: number;
          price_per_carat?: number | null;
          compare_price?: number | null;
          currency?: string;
          price_mode?: PriceModeValue;
          base_currency?: string;
          price_rule_notes?: string | null;
          tax_status?: string | null;
          tax_class?: string | null;
          hsn_code?: string | null;
          gst_rate?: number | null;
          gst_exemption_reason?: string | null;
          tax_inclusive?: boolean;
          carat_weight?: number | null;
          ratti_weight?: number | null;
          origin?: string | null;
          shape?: string | null;
          treatment?: string;
          color_grade?: string | null;
          clarity?: string | null;
          certification?: string | null;
          quality_label?: string | null;
          gender?: string | null;
          metal_purity?: string | null;
          setting_type?: string | null;
          chain_type?: string | null;
          bead_size_mm?: number | null;
          bead_weight?: number | null;
          rudraksha_origin?: string | null;
          certificate_number?: string | null;
          certificate_lab?: string | null;
          certificate_status?: CertificateStatusValue;
          certificate_issue_date?: string | null;
          planet?: string | null;
          vedic_name?: string | null;
          hindi_name?: string | null;
          chakra?: string | null;
          rashi?: string | null;
          finger?: string | null;
          wearing_day?: string | null;
          wearing_metal?: string | null;
          mukhi_count?: number | null;
          xray_certified?: boolean;
          xray_certificate_number?: string | null;
          ruling_deity?: string | null;
          deity?: string | null;
          rudraksha_type?: string | null;
          energization_eligible?: boolean;
          jewellery_type?: string | null;
          base_metal?: string | null;
          metal_weight_grams?: number | null;
          size_label?: string | null;
          ring_size?: string | null;
          design_code?: string | null;
          making_charge?: number | null;
          ready_stock?: boolean;
          return_eligibility?: ReturnEligibilityValue;
          return_window_days?: number;
          legal_disclosure_text?: string | null;
          treatment_disclosure?: string | null;
          care_instructions?: string | null;
          high_value_review_required?: boolean;
          composition?: string | null;
          dimensions_mm?: Json | null;
          short_desc?: string | null;
          description?: string | null;
          vedic_significance?: string | null;
          mantra?: string | null;
          benefits?: Json;
          wearing_guide?: string | null;
          expert_note?: string | null;
          expert_id?: string | null;
          images?: Json;
          certificate_url?: string | null;
          certificate_file_url?: string | null;
          certificate_display_enabled?: boolean;
          video_url?: string | null;
          thumbnail_url?: string | null;
          availability_status?: AvailabilityStatusValue;
          stock_status?: StockStatusValue;
          sold_individually?: boolean;
          backorders_allowed?: boolean;
          manual_reserve_enabled?: boolean;
          reserved_quantity?: number;
          reserved_until?: string | null;
          reserved_by_customer_id?: string | null;
          reserved_by_admin_id?: string | null;
          reservation_note?: string | null;
          in_stock?: boolean;
          stock_quantity?: number;
          low_stock_threshold?: number;
          featured?: boolean;
          is_directors_pick?: boolean;
          configurator_enabled?: boolean;
          is_active?: boolean;
          display_order?: number;
          meta_title?: string | null;
          meta_description?: string | null;
          seo_keywords?: string[];
          canonical_category_slug?: string | null;
          last_import_batch_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          sku?: string;
          name?: string;
          slug?: string;
          category?: string;
          sub_category?: string | null;
          product_type?: ProductTypeValue;
          catalog_family?: string | null;
          tag_number?: string | null;
          import_warnings?: Json;
          legacy_woo_id?: number | null;
          legacy_permalink?: string | null;
          legacy_status?: string | null;
          legacy_catalog_visibility?: string | null;
          legacy_type?: string | null;
          legacy_data?: Json;
          legacy_import_warnings?: Json;
          price?: number;
          price_per_carat?: number | null;
          compare_price?: number | null;
          currency?: string;
          price_mode?: PriceModeValue;
          base_currency?: string;
          price_rule_notes?: string | null;
          tax_status?: string | null;
          tax_class?: string | null;
          hsn_code?: string | null;
          gst_rate?: number | null;
          gst_exemption_reason?: string | null;
          tax_inclusive?: boolean;
          carat_weight?: number | null;
          ratti_weight?: number | null;
          origin?: string | null;
          shape?: string | null;
          treatment?: string;
          color_grade?: string | null;
          clarity?: string | null;
          certification?: string | null;
          quality_label?: string | null;
          gender?: string | null;
          metal_purity?: string | null;
          setting_type?: string | null;
          chain_type?: string | null;
          bead_size_mm?: number | null;
          bead_weight?: number | null;
          rudraksha_origin?: string | null;
          certificate_number?: string | null;
          certificate_lab?: string | null;
          certificate_status?: CertificateStatusValue;
          certificate_issue_date?: string | null;
          planet?: string | null;
          vedic_name?: string | null;
          hindi_name?: string | null;
          chakra?: string | null;
          rashi?: string | null;
          finger?: string | null;
          wearing_day?: string | null;
          wearing_metal?: string | null;
          mukhi_count?: number | null;
          xray_certified?: boolean;
          xray_certificate_number?: string | null;
          ruling_deity?: string | null;
          deity?: string | null;
          rudraksha_type?: string | null;
          energization_eligible?: boolean;
          jewellery_type?: string | null;
          base_metal?: string | null;
          metal_weight_grams?: number | null;
          size_label?: string | null;
          ring_size?: string | null;
          design_code?: string | null;
          making_charge?: number | null;
          ready_stock?: boolean;
          return_eligibility?: ReturnEligibilityValue;
          return_window_days?: number;
          legal_disclosure_text?: string | null;
          treatment_disclosure?: string | null;
          care_instructions?: string | null;
          high_value_review_required?: boolean;
          composition?: string | null;
          dimensions_mm?: Json | null;
          short_desc?: string | null;
          description?: string | null;
          vedic_significance?: string | null;
          mantra?: string | null;
          benefits?: Json;
          wearing_guide?: string | null;
          expert_note?: string | null;
          expert_id?: string | null;
          images?: Json;
          certificate_url?: string | null;
          certificate_file_url?: string | null;
          certificate_display_enabled?: boolean;
          video_url?: string | null;
          thumbnail_url?: string | null;
          availability_status?: AvailabilityStatusValue;
          stock_status?: StockStatusValue;
          sold_individually?: boolean;
          backorders_allowed?: boolean;
          manual_reserve_enabled?: boolean;
          reserved_quantity?: number;
          reserved_until?: string | null;
          reserved_by_customer_id?: string | null;
          reserved_by_admin_id?: string | null;
          reservation_note?: string | null;
          in_stock?: boolean;
          stock_quantity?: number;
          low_stock_threshold?: number;
          featured?: boolean;
          is_directors_pick?: boolean;
          configurator_enabled?: boolean;
          is_active?: boolean;
          display_order?: number;
          meta_title?: string | null;
          meta_description?: string | null;
          seo_keywords?: string[];
          canonical_category_slug?: string | null;
          last_import_batch_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      experts: {
        Row: {
          id: string;
          name: string;
          title: string | null;
          photo_url: string | null;
          tier: string;
          specialty: string | null;
          years_experience: number | null;
          bio: string | null;
          personal_quote: string | null;
          credentials: string[] | null;
          languages: string[] | null;
          rating: number;
          consultation_count: number;
          is_available: boolean;
          availability_schedule: Json | null;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          title?: string | null;
          photo_url?: string | null;
          tier: string;
          specialty?: string | null;
          years_experience?: number | null;
          bio?: string | null;
          personal_quote?: string | null;
          credentials?: string[] | null;
          languages?: string[] | null;
          rating?: number;
          consultation_count?: number;
          is_available?: boolean;
          availability_schedule?: Json | null;
          sort_order?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          title?: string | null;
          photo_url?: string | null;
          tier?: string;
          specialty?: string | null;
          years_experience?: number | null;
          bio?: string | null;
          personal_quote?: string | null;
          credentials?: string[] | null;
          languages?: string[] | null;
          rating?: number;
          consultation_count?: number;
          is_available?: boolean;
          availability_schedule?: Json | null;
          sort_order?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      customer_profiles: {
        Row: {
          id: string;
          full_name: string | null;
          phone: string | null;
          whatsapp: string | null;
          email: string | null;
          date_of_birth: string | null;
          birth_time: string | null;
          birth_place: string | null;
          gotra: string | null;
          rashi: string | null;
          addresses: Json;
          default_address_index: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          full_name?: string | null;
          phone?: string | null;
          whatsapp?: string | null;
          email?: string | null;
          date_of_birth?: string | null;
          birth_time?: string | null;
          birth_place?: string | null;
          gotra?: string | null;
          rashi?: string | null;
          addresses?: Json;
          default_address_index?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          full_name?: string | null;
          phone?: string | null;
          whatsapp?: string | null;
          email?: string | null;
          date_of_birth?: string | null;
          birth_time?: string | null;
          birth_place?: string | null;
          gotra?: string | null;
          rashi?: string | null;
          addresses?: Json;
          default_address_index?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      customer_preferences: {
        Row: {
          customer_id: string;
          notification_preferences: Json;
          family_birth_profiles: Json;
          security_preferences: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          customer_id: string;
          notification_preferences?: Json;
          family_birth_profiles?: Json;
          security_preferences?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          customer_id?: string;
          notification_preferences?: Json;
          family_birth_profiles?: Json;
          security_preferences?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      orders: {
        Row: {
          id: string;
          order_number: string;
          customer_id: string | null;
          guest_email: string | null;
          guest_phone: string | null;
          guest_name: string | null;
          items: Json;
          subtotal: number;
          jewelry_charges: number;
          metal_charges: number;
          certification_charges: number;
          energization_charges: number;
          shipping_cost: number;
          discount: number;
          coupon_code: string | null;
          gst_amount: number;
          tax_breakdown: Json;
          total: number;
          shipping_address: Json;
          shipping_method: string | null;
          billing_address: Json;
          buyer_business_name: string | null;
          buyer_gstin: string | null;
          tax_invoice_required: boolean;
          invoice_status: string;
          invoice_generated_at: string | null;
          invoice_pdf_path: string | null;
          refund_status: string;
          return_status: string;
          policy_acceptance: Json;
          compliance_flags: Json;
          special_instructions: string | null;
          include_energization: boolean;
          energization_type: string | null;
          ceremony_gotra: string | null;
          ceremony_dob: string | null;
          ceremony_rashi: string | null;
          record_ceremony: boolean;
          payment_method: string | null;
          razorpay_order_id: string | null;
          razorpay_payment_id: string | null;
          razorpay_signature: string | null;
          payment_status: string;
          payment_attempts: number;
          payment_failure_reason: string | null;
          payment_review_reason: string | null;
          amount_verified_at: string | null;
          last_payment_event_id: string | null;
          status: string;
          guest_access_token: string | null;
          reservation_expires_at: string | null;
          confirmation_email_sent_at: string | null;
          admin_notification_sent_at: string | null;
          tracking_number: string | null;
          tracking_url: string | null;
          estimated_delivery: string | null;
          assigned_to: string | null;
          internal_notes: string | null;
          invoice_number: string | null;
          invoice_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          order_number?: string;
          customer_id?: string | null;
          guest_email?: string | null;
          guest_phone?: string | null;
          guest_name?: string | null;
          items: Json;
          subtotal: number;
          jewelry_charges?: number;
          metal_charges?: number;
          certification_charges?: number;
          energization_charges?: number;
          shipping_cost?: number;
          discount?: number;
          coupon_code?: string | null;
          gst_amount?: number;
          tax_breakdown?: Json;
          total: number;
          shipping_address: Json;
          shipping_method?: string | null;
          billing_address?: Json;
          buyer_business_name?: string | null;
          buyer_gstin?: string | null;
          tax_invoice_required?: boolean;
          invoice_status?: string;
          invoice_generated_at?: string | null;
          invoice_pdf_path?: string | null;
          refund_status?: string;
          return_status?: string;
          policy_acceptance?: Json;
          compliance_flags?: Json;
          special_instructions?: string | null;
          include_energization?: boolean;
          energization_type?: string | null;
          ceremony_gotra?: string | null;
          ceremony_dob?: string | null;
          ceremony_rashi?: string | null;
          record_ceremony?: boolean;
          payment_method?: string | null;
          razorpay_order_id?: string | null;
          razorpay_payment_id?: string | null;
          razorpay_signature?: string | null;
          payment_status?: string;
          payment_attempts?: number;
          payment_failure_reason?: string | null;
          payment_review_reason?: string | null;
          amount_verified_at?: string | null;
          last_payment_event_id?: string | null;
          status?: string;
          guest_access_token?: string | null;
          reservation_expires_at?: string | null;
          confirmation_email_sent_at?: string | null;
          admin_notification_sent_at?: string | null;
          tracking_number?: string | null;
          tracking_url?: string | null;
          estimated_delivery?: string | null;
          assigned_to?: string | null;
          internal_notes?: string | null;
          invoice_number?: string | null;
          invoice_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          order_number?: string;
          customer_id?: string | null;
          guest_email?: string | null;
          guest_phone?: string | null;
          guest_name?: string | null;
          items?: Json;
          subtotal?: number;
          jewelry_charges?: number;
          metal_charges?: number;
          certification_charges?: number;
          energization_charges?: number;
          shipping_cost?: number;
          discount?: number;
          coupon_code?: string | null;
          gst_amount?: number;
          tax_breakdown?: Json;
          total?: number;
          shipping_address?: Json;
          shipping_method?: string | null;
          billing_address?: Json;
          buyer_business_name?: string | null;
          buyer_gstin?: string | null;
          tax_invoice_required?: boolean;
          invoice_status?: string;
          invoice_generated_at?: string | null;
          invoice_pdf_path?: string | null;
          refund_status?: string;
          return_status?: string;
          policy_acceptance?: Json;
          compliance_flags?: Json;
          special_instructions?: string | null;
          include_energization?: boolean;
          energization_type?: string | null;
          ceremony_gotra?: string | null;
          ceremony_dob?: string | null;
          ceremony_rashi?: string | null;
          record_ceremony?: boolean;
          payment_method?: string | null;
          razorpay_order_id?: string | null;
          razorpay_payment_id?: string | null;
          razorpay_signature?: string | null;
          payment_status?: string;
          payment_attempts?: number;
          payment_failure_reason?: string | null;
          payment_review_reason?: string | null;
          amount_verified_at?: string | null;
          last_payment_event_id?: string | null;
          status?: string;
          guest_access_token?: string | null;
          reservation_expires_at?: string | null;
          confirmation_email_sent_at?: string | null;
          admin_notification_sent_at?: string | null;
          tracking_number?: string | null;
          tracking_url?: string | null;
          estimated_delivery?: string | null;
          assigned_to?: string | null;
          internal_notes?: string | null;
          invoice_number?: string | null;
          invoice_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      carts: {
        Row: {
          id: string;
          customer_id: string | null;
          guest_session_id: string | null;
          status: string;
          item_count: number;
          subtotal: number;
          currency: string;
          last_event_at: string | null;
          merged_at: string | null;
          order_id: string | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          customer_id?: string | null;
          guest_session_id?: string | null;
          status?: string;
          item_count?: number;
          subtotal?: number;
          currency?: string;
          last_event_at?: string | null;
          merged_at?: string | null;
          order_id?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          customer_id?: string | null;
          guest_session_id?: string | null;
          status?: string;
          item_count?: number;
          subtotal?: number;
          currency?: string;
          last_event_at?: string | null;
          merged_at?: string | null;
          order_id?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      cart_items: {
        Row: {
          id: string;
          cart_id: string;
          line_key: string;
          product_id: string;
          configuration_id: string | null;
          quantity: number;
          sku: string | null;
          tag_number: string | null;
          name_snapshot: string;
          category_snapshot: string | null;
          image_url_snapshot: string | null;
          price_snapshot: number;
          line_total_snapshot: number;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          cart_id: string;
          line_key: string;
          product_id: string;
          configuration_id?: string | null;
          quantity?: number;
          sku?: string | null;
          tag_number?: string | null;
          name_snapshot: string;
          category_snapshot?: string | null;
          image_url_snapshot?: string | null;
          price_snapshot?: number;
          line_total_snapshot?: number;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          cart_id?: string;
          line_key?: string;
          product_id?: string;
          configuration_id?: string | null;
          quantity?: number;
          sku?: string | null;
          tag_number?: string | null;
          name_snapshot?: string;
          category_snapshot?: string | null;
          image_url_snapshot?: string | null;
          price_snapshot?: number;
          line_total_snapshot?: number;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      cart_events: {
        Row: {
          id: string;
          customer_id: string | null;
          guest_session_id: string | null;
          cart_id: string | null;
          cart_item_id: string | null;
          product_id: string | null;
          event_type: string;
          quantity: number | null;
          value: number | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          customer_id?: string | null;
          guest_session_id?: string | null;
          cart_id?: string | null;
          cart_item_id?: string | null;
          product_id?: string | null;
          event_type: string;
          quantity?: number | null;
          value?: number | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          customer_id?: string | null;
          guest_session_id?: string | null;
          cart_id?: string | null;
          cart_item_id?: string | null;
          product_id?: string | null;
          event_type?: string;
          quantity?: number | null;
          value?: number | null;
          metadata?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      shipping_methods: {
        Row: {
          id: string;
          label: string;
          description: string | null;
          cost: number;
          free_above: number | null;
          min_order_amount: number | null;
          max_order_amount: number | null;
          estimated_days_min: number | null;
          estimated_days_max: number | null;
          zones: string[];
          is_active: boolean;
          sort_order: number;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          label: string;
          description?: string | null;
          cost?: number;
          free_above?: number | null;
          min_order_amount?: number | null;
          max_order_amount?: number | null;
          estimated_days_min?: number | null;
          estimated_days_max?: number | null;
          zones?: string[];
          is_active?: boolean;
          sort_order?: number;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          label?: string;
          description?: string | null;
          cost?: number;
          free_above?: number | null;
          min_order_amount?: number | null;
          max_order_amount?: number | null;
          estimated_days_min?: number | null;
          estimated_days_max?: number | null;
          zones?: string[];
          is_active?: boolean;
          sort_order?: number;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      coupon_redemptions: {
        Row: {
          id: string;
          coupon_id: string;
          order_id: string;
          customer_id: string | null;
          guest_email_hash: string | null;
          discount_amount: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          coupon_id: string;
          order_id: string;
          customer_id?: string | null;
          guest_email_hash?: string | null;
          discount_amount?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          coupon_id?: string;
          order_id?: string;
          customer_id?: string | null;
          guest_email_hash?: string | null;
          discount_amount?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      payment_events: {
        Row: {
          id: string;
          provider: string;
          event_id: string | null;
          event_type: string;
          order_id: string | null;
          razorpay_order_id: string | null;
          razorpay_payment_id: string | null;
          signature_valid: boolean | null;
          amount_paise: number | null;
          expected_paise: number | null;
          status: string;
          payload: Json;
          processed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          provider?: string;
          event_id?: string | null;
          event_type: string;
          order_id?: string | null;
          razorpay_order_id?: string | null;
          razorpay_payment_id?: string | null;
          signature_valid?: boolean | null;
          amount_paise?: number | null;
          expected_paise?: number | null;
          status?: string;
          payload?: Json;
          processed_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          provider?: string;
          event_id?: string | null;
          event_type?: string;
          order_id?: string | null;
          razorpay_order_id?: string | null;
          razorpay_payment_id?: string | null;
          signature_valid?: boolean | null;
          amount_paise?: number | null;
          expected_paise?: number | null;
          status?: string;
          payload?: Json;
          processed_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      jewelry_designs: {
        Row: {
          id: string;
          name: string;
          setting_type: string;
          image_url: string | null;
          description: string | null;
          making_charges: Json;
          estimated_metal_weight: Json | null;
          is_custom: boolean;
          sort_order: number;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          setting_type: string;
          image_url?: string | null;
          description?: string | null;
          making_charges: Json;
          estimated_metal_weight?: Json | null;
          is_custom?: boolean;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          setting_type?: string;
          image_url?: string | null;
          description?: string | null;
          making_charges?: Json;
          estimated_metal_weight?: Json | null;
          is_custom?: boolean;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      energization_options: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          price: number;
          duration: string | null;
          includes: Json;
          includes_video: boolean;
          sort_order: number;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          price: number;
          duration?: string | null;
          includes?: Json;
          includes_video?: boolean;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          price?: number;
          duration?: string | null;
          includes?: Json;
          includes_video?: boolean;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      certification_labs: {
        Row: {
          id: string;
          name: string;
          full_name: string | null;
          extra_charge: number;
          turnaround_days: number;
          sample_cert_url: string | null;
          description: string | null;
          is_default: boolean;
          sort_order: number;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          full_name?: string | null;
          extra_charge?: number;
          turnaround_days?: number;
          sample_cert_url?: string | null;
          description?: string | null;
          is_default?: boolean;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          full_name?: string | null;
          extra_charge?: number;
          turnaround_days?: number;
          sample_cert_url?: string | null;
          description?: string | null;
          is_default?: boolean;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      product_configurations: {
        Row: {
          id: string;
          session_id: string | null;
          customer_id: string | null;
          product_id: string;
          setting_type: string | null;
          design_id: string | null;
          custom_design_url: string | null;
          custom_design_status: string | null;
          metal: string | null;
          ring_size: string | null;
          chain_length: string | null;
          certification_id: string | null;
          energization_id: string | null;
          gem_price: number | null;
          making_charge: number | null;
          metal_price: number | null;
          metal_weight_grams: number | null;
          gold_rate_per_gram: number | null;
          certification_fee: number | null;
          energization_fee: number | null;
          custom_design_fee: number | null;
          total_price: number | null;
          delivery_eta_min_days: number | null;
          delivery_eta_max_days: number | null;
          delivery_eta_label: string | null;
          configuration_snapshot: Json | null;
          pricing_snapshot: Json | null;
          status: string;
          order_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          session_id?: string | null;
          customer_id?: string | null;
          product_id: string;
          setting_type?: string | null;
          design_id?: string | null;
          custom_design_url?: string | null;
          custom_design_status?: string | null;
          metal?: string | null;
          ring_size?: string | null;
          chain_length?: string | null;
          certification_id?: string | null;
          energization_id?: string | null;
          gem_price?: number | null;
          making_charge?: number | null;
          metal_price?: number | null;
          metal_weight_grams?: number | null;
          gold_rate_per_gram?: number | null;
          certification_fee?: number | null;
          energization_fee?: number | null;
          custom_design_fee?: number | null;
          total_price?: number | null;
          delivery_eta_min_days?: number | null;
          delivery_eta_max_days?: number | null;
          delivery_eta_label?: string | null;
          configuration_snapshot?: Json | null;
          pricing_snapshot?: Json | null;
          status?: string;
          order_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          session_id?: string | null;
          customer_id?: string | null;
          product_id?: string;
          setting_type?: string | null;
          design_id?: string | null;
          custom_design_url?: string | null;
          custom_design_status?: string | null;
          metal?: string | null;
          ring_size?: string | null;
          chain_length?: string | null;
          certification_id?: string | null;
          energization_id?: string | null;
          gem_price?: number | null;
          making_charge?: number | null;
          metal_price?: number | null;
          metal_weight_grams?: number | null;
          gold_rate_per_gram?: number | null;
          certification_fee?: number | null;
          energization_fee?: number | null;
          custom_design_fee?: number | null;
          total_price?: number | null;
          delivery_eta_min_days?: number | null;
          delivery_eta_max_days?: number | null;
          delivery_eta_label?: string | null;
          configuration_snapshot?: Json | null;
          pricing_snapshot?: Json | null;
          status?: string;
          order_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      consultation_plans: {
        Row: {
          id: string;
          title: string;
          slug: string;
          description: string | null;
          amount_inr: number;
          amount_usd: number | null;
          currency: string;
          duration_minutes: number | null;
          is_active: boolean;
          sort_order: number;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          slug: string;
          description?: string | null;
          amount_inr: number;
          amount_usd?: number | null;
          currency?: string;
          duration_minutes?: number | null;
          is_active?: boolean;
          sort_order?: number;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          slug?: string;
          description?: string | null;
          amount_inr?: number;
          amount_usd?: number | null;
          currency?: string;
          duration_minutes?: number | null;
          is_active?: boolean;
          sort_order?: number;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      consultations: {
        Row: {
          id: string;
          customer_id: string | null;
          expert_id: string | null;
          plan_id: string | null;
          plan_title_snapshot: string | null;
          plan_description_snapshot: string | null;
          full_name: string;
          email: string;
          phone: string | null;
          date_of_birth: string | null;
          birth_time: string | null;
          birth_place: string | null;
          life_situation: string | null;
          consultation_type: string | null;
          mode: string | null;
          preferred_date: string | null;
          preferred_time: string | null;
          scheduled_date: string | null;
          scheduled_time: string | null;
          scheduled_mode: string | null;
          meeting_link: string | null;
          admin_schedule_notes: string | null;
          scheduled_at: string | null;
          scheduled_email_sent_at: string | null;
          scheduled_notification_sent_at: string | null;
          message: string | null;
          amount_inr: number | null;
          amount_paise: number | null;
          currency: string;
          payment_status: string;
          payment_method: string | null;
          razorpay_order_id: string | null;
          razorpay_payment_id: string | null;
          razorpay_signature: string | null;
          payment_attempts: number;
          payment_failure_reason: string | null;
          payment_review_reason: string | null;
          amount_verified_at: string | null;
          confirmation_email_sent_at: string | null;
          admin_notification_sent_at: string | null;
          completed_email_sent_at: string | null;
          completed_at: string | null;
          payment_metadata: Json;
          status: string;
          assigned_expert: string | null;
          internal_notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          customer_id?: string | null;
          expert_id?: string | null;
          plan_id?: string | null;
          plan_title_snapshot?: string | null;
          plan_description_snapshot?: string | null;
          full_name: string;
          email: string;
          phone?: string | null;
          date_of_birth?: string | null;
          birth_time?: string | null;
          birth_place?: string | null;
          life_situation?: string | null;
          consultation_type?: string | null;
          mode?: string | null;
          preferred_date?: string | null;
          preferred_time?: string | null;
          scheduled_date?: string | null;
          scheduled_time?: string | null;
          scheduled_mode?: string | null;
          meeting_link?: string | null;
          admin_schedule_notes?: string | null;
          scheduled_at?: string | null;
          scheduled_email_sent_at?: string | null;
          scheduled_notification_sent_at?: string | null;
          message?: string | null;
          amount_inr?: number | null;
          amount_paise?: number | null;
          currency?: string;
          payment_status?: string;
          payment_method?: string | null;
          razorpay_order_id?: string | null;
          razorpay_payment_id?: string | null;
          razorpay_signature?: string | null;
          payment_attempts?: number;
          payment_failure_reason?: string | null;
          payment_review_reason?: string | null;
          amount_verified_at?: string | null;
          confirmation_email_sent_at?: string | null;
          admin_notification_sent_at?: string | null;
          completed_email_sent_at?: string | null;
          completed_at?: string | null;
          payment_metadata?: Json;
          status?: string;
          assigned_expert?: string | null;
          internal_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          customer_id?: string | null;
          expert_id?: string | null;
          plan_id?: string | null;
          plan_title_snapshot?: string | null;
          plan_description_snapshot?: string | null;
          full_name?: string;
          email?: string;
          phone?: string | null;
          date_of_birth?: string | null;
          birth_time?: string | null;
          birth_place?: string | null;
          life_situation?: string | null;
          consultation_type?: string | null;
          mode?: string | null;
          preferred_date?: string | null;
          preferred_time?: string | null;
          scheduled_date?: string | null;
          scheduled_time?: string | null;
          scheduled_mode?: string | null;
          meeting_link?: string | null;
          admin_schedule_notes?: string | null;
          scheduled_at?: string | null;
          scheduled_email_sent_at?: string | null;
          scheduled_notification_sent_at?: string | null;
          message?: string | null;
          amount_inr?: number | null;
          amount_paise?: number | null;
          currency?: string;
          payment_status?: string;
          payment_method?: string | null;
          razorpay_order_id?: string | null;
          razorpay_payment_id?: string | null;
          razorpay_signature?: string | null;
          payment_attempts?: number;
          payment_failure_reason?: string | null;
          payment_review_reason?: string | null;
          amount_verified_at?: string | null;
          confirmation_email_sent_at?: string | null;
          admin_notification_sent_at?: string | null;
          completed_email_sent_at?: string | null;
          completed_at?: string | null;
          payment_metadata?: Json;
          status?: string;
          assigned_expert?: string | null;
          internal_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      enquiries: {
        Row: {
          id: string;
          name: string;
          email: string;
          phone: string | null;
          subject: string | null;
          message: string;
          product_id: string | null;
          source: string;
          status: string;
          assigned_to: string | null;
          follow_up_date: string | null;
          internal_notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          email: string;
          phone?: string | null;
          subject?: string | null;
          message: string;
          product_id?: string | null;
          source?: string;
          status?: string;
          assigned_to?: string | null;
          follow_up_date?: string | null;
          internal_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          email?: string;
          phone?: string | null;
          subject?: string | null;
          message?: string;
          product_id?: string | null;
          source?: string;
          status?: string;
          assigned_to?: string | null;
          follow_up_date?: string | null;
          internal_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      reviews: {
        Row: {
          id: string;
          product_id: string;
          order_id: string | null;
          customer_id: string | null;
          customer_name: string;
          customer_location: string | null;
          rating: number | null;
          title: string | null;
          review_text: string | null;
          images: Json;
          is_verified: boolean;
          is_approved: boolean;
          is_featured: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          product_id: string;
          order_id?: string | null;
          customer_id?: string | null;
          customer_name: string;
          customer_location?: string | null;
          rating?: number | null;
          title?: string | null;
          review_text?: string | null;
          images?: Json;
          is_verified?: boolean;
          is_approved?: boolean;
          is_featured?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          product_id?: string;
          order_id?: string | null;
          customer_id?: string | null;
          customer_name?: string;
          customer_location?: string | null;
          rating?: number | null;
          title?: string | null;
          review_text?: string | null;
          images?: Json;
          is_verified?: boolean;
          is_approved?: boolean;
          is_featured?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      coupons: {
        Row: {
          id: string;
          code: string;
          discount_type: string;
          discount_value: number;
          min_order_amount: number;
          max_discount: number | null;
          usage_limit: number | null;
          usage_limit_per_customer: number | null;
          used_count: number;
          valid_from: string;
          valid_until: string | null;
          applies_to_product_ids: string[];
          applies_to_category_slugs: string[];
          excluded_product_ids: string[];
          excluded_category_slugs: string[];
          first_time_customers_only: boolean;
          metadata: Json;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          code: string;
          discount_type: string;
          discount_value: number;
          min_order_amount?: number;
          max_discount?: number | null;
          usage_limit?: number | null;
          usage_limit_per_customer?: number | null;
          used_count?: number;
          valid_from?: string;
          valid_until?: string | null;
          applies_to_product_ids?: string[];
          applies_to_category_slugs?: string[];
          excluded_product_ids?: string[];
          excluded_category_slugs?: string[];
          first_time_customers_only?: boolean;
          metadata?: Json;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          code?: string;
          discount_type?: string;
          discount_value?: number;
          min_order_amount?: number;
          max_discount?: number | null;
          usage_limit?: number | null;
          usage_limit_per_customer?: number | null;
          used_count?: number;
          valid_from?: string;
          valid_until?: string | null;
          applies_to_product_ids?: string[];
          applies_to_category_slugs?: string[];
          excluded_product_ids?: string[];
          excluded_category_slugs?: string[];
          first_time_customers_only?: boolean;
          metadata?: Json;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      saved_items: {
        Row: {
          id: string;
          customer_id: string;
          product_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          customer_id: string;
          product_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          customer_id?: string;
          product_id?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      admin_activity_log: {
        Row: {
          id: string;
          user_id: string;
          action: string;
          resource_type: string | null;
          resource_id: string | null;
          details: Json | null;
          ip_address: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          action: string;
          resource_type?: string | null;
          resource_id?: string | null;
          details?: Json | null;
          ip_address?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          action?: string;
          resource_type?: string | null;
          resource_id?: string | null;
          details?: Json | null;
          ip_address?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      team_members: {
        Row: {
          id: string;
          role: string;
          name: string;
          is_active: boolean;
          permissions: Json;
          created_at: string;
        };
        Insert: {
          id: string;
          role: string;
          name: string;
          is_active?: boolean;
          permissions?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          role?: string;
          name?: string;
          is_active?: boolean;
          permissions?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      product_categories: {
        Row: {
          id: string;
          parent_id: string | null;
          slug: string;
          name: string;
          family: string;
          legacy_names: string[];
          description: string | null;
          image_url: string | null;
          hover_image_url: string | null;
          homepage_subtitle: string | null;
          homepage_badge: string | null;
          show_on_homepage: boolean;
          homepage_slot: string | null;
          cta_label: string | null;
          accent_color: string | null;
          seo_title: string | null;
          seo_description: string | null;
          meta_keywords: string[];
          canonical_path: string | null;
          sort_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          parent_id?: string | null;
          slug: string;
          name: string;
          family: string;
          legacy_names?: string[];
          description?: string | null;
          image_url?: string | null;
          hover_image_url?: string | null;
          homepage_subtitle?: string | null;
          homepage_badge?: string | null;
          show_on_homepage?: boolean;
          homepage_slot?: string | null;
          cta_label?: string | null;
          accent_color?: string | null;
          seo_title?: string | null;
          seo_description?: string | null;
          meta_keywords?: string[];
          canonical_path?: string | null;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          parent_id?: string | null;
          slug?: string;
          name?: string;
          family?: string;
          legacy_names?: string[];
          description?: string | null;
          image_url?: string | null;
          hover_image_url?: string | null;
          homepage_subtitle?: string | null;
          homepage_badge?: string | null;
          show_on_homepage?: boolean;
          homepage_slot?: string | null;
          cta_label?: string | null;
          accent_color?: string | null;
          seo_title?: string | null;
          seo_description?: string | null;
          meta_keywords?: string[];
          canonical_path?: string | null;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      product_category_assignments: {
        Row: {
          id: string;
          product_id: string;
          category_id: string;
          is_primary: boolean;
          sort_order: number;
          legacy_path: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          product_id: string;
          category_id: string;
          is_primary?: boolean;
          sort_order?: number;
          legacy_path?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          product_id?: string;
          category_id?: string;
          is_primary?: boolean;
          sort_order?: number;
          legacy_path?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      gem_categories: {
        Row: {
          id: string;
          name: string;
          slug: string;
          type: string;
          sanskrit_name: string | null;
          planet: string | null;
          emoji: string | null;
          color: string | null;
          image_url: string | null;
          hover_image_url: string | null;
          description: string | null;
          display_locations: string | null;
          is_rare: boolean;
          featured_on_homepage: boolean;
          sort_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          type: string;
          sanskrit_name?: string | null;
          planet?: string | null;
          emoji?: string | null;
          color?: string | null;
          image_url?: string | null;
          hover_image_url?: string | null;
          description?: string | null;
          display_locations?: string | null;
          is_rare?: boolean;
          featured_on_homepage?: boolean;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          type?: string;
          sanskrit_name?: string | null;
          planet?: string | null;
          emoji?: string | null;
          color?: string | null;
          image_url?: string | null;
          hover_image_url?: string | null;
          description?: string | null;
          display_locations?: string | null;
          is_rare?: boolean;
          featured_on_homepage?: boolean;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      metals: {
        Row: {
          id: string;
          name: string;
          slug: string;
          purity: string | null;
          price_per_gram: number;
          description: string | null;
          is_active: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          purity?: string | null;
          price_per_gram: number;
          description?: string | null;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          purity?: string | null;
          price_per_gram?: number;
          description?: string | null;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      gold_rate_cache: {
        Row: {
          id: number;
          gold_22k_per_gram: number;
          gold_18k_per_gram: number | null;
          silver_per_gram: number | null;
          source: string | null;
          fetched_at: string;
          manual_override: boolean;
        };
        Insert: {
          id?: number;
          gold_22k_per_gram: number;
          gold_18k_per_gram?: number | null;
          silver_per_gram?: number | null;
          source?: string | null;
          fetched_at?: string;
          manual_override?: boolean;
        };
        Update: {
          id?: number;
          gold_22k_per_gram?: number;
          gold_18k_per_gram?: number | null;
          silver_per_gram?: number | null;
          source?: string | null;
          fetched_at?: string;
          manual_override?: boolean;
        };
        Relationships: [];
      };
      notification_log: {
        Row: {
          id: string;
          type: string;
          recipient: string;
          template: string | null;
          context: Json | null;
          status: string;
          error_message: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          type: string;
          recipient: string;
          template?: string | null;
          context?: Json | null;
          status?: string;
          error_message?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          type?: string;
          recipient?: string;
          template?: string | null;
          context?: Json | null;
          status?: string;
          error_message?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}

// Convenience type aliases
export type Product = Database['public']['Tables']['products']['Row'];
export type ProductInsert = Database['public']['Tables']['products']['Insert'];
export type Expert = Database['public']['Tables']['experts']['Row'];
export type CustomerProfile = Database['public']['Tables']['customer_profiles']['Row'];
export type CustomerPreference = Database['public']['Tables']['customer_preferences']['Row'];
export type Order = Database['public']['Tables']['orders']['Row'];
export type OrderInsert = Database['public']['Tables']['orders']['Insert'];
export type ServerCart = Database['public']['Tables']['carts']['Row'];
export type ServerCartItem = Database['public']['Tables']['cart_items']['Row'];
export type CartEvent = Database['public']['Tables']['cart_events']['Row'];
export type ShippingMethod = Database['public']['Tables']['shipping_methods']['Row'];
export type CouponRedemption = Database['public']['Tables']['coupon_redemptions']['Row'];
export type PaymentEvent = Database['public']['Tables']['payment_events']['Row'];
export type ConsultationPlan = Database['public']['Tables']['consultation_plans']['Row'];
export type ConsultationPlanInsert = Database['public']['Tables']['consultation_plans']['Insert'];
export type JewelryDesign = Database['public']['Tables']['jewelry_designs']['Row'];
export type EnergizationOption = Database['public']['Tables']['energization_options']['Row'];
export type CertificationLab = Database['public']['Tables']['certification_labs']['Row'];
export type ProductConfiguration = Database['public']['Tables']['product_configurations']['Row'];
export type Consultation = Database['public']['Tables']['consultations']['Row'];
export type Enquiry = Database['public']['Tables']['enquiries']['Row'];
export type Review = Database['public']['Tables']['reviews']['Row'];
export type Coupon = Database['public']['Tables']['coupons']['Row'];
export type SavedItem = Database['public']['Tables']['saved_items']['Row'];
export type TeamMember = Database['public']['Tables']['team_members']['Row'];
export type GoldRateCache = Database['public']['Tables']['gold_rate_cache']['Row'];
export type NotificationLog = Database['public']['Tables']['notification_log']['Row'];
export type ProductCategoryRow = Database['public']['Tables']['product_categories']['Row'];
export type ProductCategoryInsert = Database['public']['Tables']['product_categories']['Insert'];
export type ProductCategoryAssignmentRow = Database['public']['Tables']['product_category_assignments']['Row'];
export type GemCategoryRow = Database['public']['Tables']['gem_categories']['Row'];
export type GemCategoryInsert = Database['public']['Tables']['gem_categories']['Insert'];
export type Metal = Database['public']['Tables']['metals']['Row'];
export type MetalInsert = Database['public']['Tables']['metals']['Insert'];
