export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      products: {
        Row: {
          id: string;
          sku: string;
          name: string;
          slug: string;
          category: string;
          sub_category: string | null;
          price: number;
          price_per_carat: number | null;
          compare_price: number | null;
          currency: string;
          carat_weight: number | null;
          ratti_weight: number | null;
          origin: string | null;
          shape: string | null;
          treatment: string;
          color_grade: string | null;
          clarity: string | null;
          certification: string | null;
          planet: string | null;
          vedic_name: string | null;
          hindi_name: string | null;
          chakra: string | null;
          rashi: string | null;
          finger: string | null;
          wearing_day: string | null;
          wearing_metal: string | null;
          mukhi_count: number | null;
          xray_certified: boolean;
          ruling_deity: string | null;
          short_desc: string | null;
          description: string | null;
          vedic_significance: string | null;
          benefits: Json;
          wearing_guide: string | null;
          expert_note: string | null;
          expert_id: string | null;
          images: Json;
          certificate_url: string | null;
          video_url: string | null;
          thumbnail_url: string | null;
          in_stock: boolean;
          stock_quantity: number;
          low_stock_threshold: number;
          featured: boolean;
          is_directors_pick: boolean;
          configurator_enabled: boolean;
          is_active: boolean;
          display_order: number;
          meta_title: string | null;
          meta_description: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          sku: string;
          name: string;
          slug: string;
          category: string;
          sub_category?: string | null;
          price: number;
          price_per_carat?: number | null;
          compare_price?: number | null;
          currency?: string;
          carat_weight?: number | null;
          ratti_weight?: number | null;
          origin?: string | null;
          shape?: string | null;
          treatment?: string;
          color_grade?: string | null;
          clarity?: string | null;
          certification?: string | null;
          planet?: string | null;
          vedic_name?: string | null;
          hindi_name?: string | null;
          chakra?: string | null;
          rashi?: string | null;
          finger?: string | null;
          wearing_day?: string | null;
          wearing_metal?: string | null;
          mukhi_count?: number | null;
          xray_certified?: boolean;
          ruling_deity?: string | null;
          short_desc?: string | null;
          description?: string | null;
          vedic_significance?: string | null;
          benefits?: Json;
          wearing_guide?: string | null;
          expert_note?: string | null;
          expert_id?: string | null;
          images?: Json;
          certificate_url?: string | null;
          video_url?: string | null;
          thumbnail_url?: string | null;
          in_stock?: boolean;
          stock_quantity?: number;
          low_stock_threshold?: number;
          featured?: boolean;
          is_directors_pick?: boolean;
          configurator_enabled?: boolean;
          is_active?: boolean;
          display_order?: number;
          meta_title?: string | null;
          meta_description?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          sku?: string;
          name?: string;
          slug?: string;
          category?: string;
          sub_category?: string | null;
          price?: number;
          price_per_carat?: number | null;
          compare_price?: number | null;
          currency?: string;
          carat_weight?: number | null;
          ratti_weight?: number | null;
          origin?: string | null;
          shape?: string | null;
          treatment?: string;
          color_grade?: string | null;
          clarity?: string | null;
          certification?: string | null;
          planet?: string | null;
          vedic_name?: string | null;
          hindi_name?: string | null;
          chakra?: string | null;
          rashi?: string | null;
          finger?: string | null;
          wearing_day?: string | null;
          wearing_metal?: string | null;
          mukhi_count?: number | null;
          xray_certified?: boolean;
          ruling_deity?: string | null;
          short_desc?: string | null;
          description?: string | null;
          vedic_significance?: string | null;
          benefits?: Json;
          wearing_guide?: string | null;
          expert_note?: string | null;
          expert_id?: string | null;
          images?: Json;
          certificate_url?: string | null;
          video_url?: string | null;
          thumbnail_url?: string | null;
          in_stock?: boolean;
          stock_quantity?: number;
          low_stock_threshold?: number;
          featured?: boolean;
          is_directors_pick?: boolean;
          configurator_enabled?: boolean;
          is_active?: boolean;
          display_order?: number;
          meta_title?: string | null;
          meta_description?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      experts: {
        Row: {
          id: string;
          name: string;
          title: string | null;
          photo_url: string | null;
          tier: string;
          specialty: string | null;
          years_experience: number | null;
          bio: string | null;
          personal_quote: string | null;
          credentials: string[] | null;
          languages: string[] | null;
          rating: number;
          consultation_count: number;
          is_available: boolean;
          availability_schedule: Json | null;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          title?: string | null;
          photo_url?: string | null;
          tier: string;
          specialty?: string | null;
          years_experience?: number | null;
          bio?: string | null;
          personal_quote?: string | null;
          credentials?: string[] | null;
          languages?: string[] | null;
          rating?: number;
          consultation_count?: number;
          is_available?: boolean;
          availability_schedule?: Json | null;
          sort_order?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          title?: string | null;
          photo_url?: string | null;
          tier?: string;
          specialty?: string | null;
          years_experience?: number | null;
          bio?: string | null;
          personal_quote?: string | null;
          credentials?: string[] | null;
          languages?: string[] | null;
          rating?: number;
          consultation_count?: number;
          is_available?: boolean;
          availability_schedule?: Json | null;
          sort_order?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      customer_profiles: {
        Row: {
          id: string;
          full_name: string | null;
          phone: string | null;
          whatsapp: string | null;
          email: string | null;
          date_of_birth: string | null;
          birth_time: string | null;
          birth_place: string | null;
          gotra: string | null;
          rashi: string | null;
          addresses: Json;
          default_address_index: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          full_name?: string | null;
          phone?: string | null;
          whatsapp?: string | null;
          email?: string | null;
          date_of_birth?: string | null;
          birth_time?: string | null;
          birth_place?: string | null;
          gotra?: string | null;
          rashi?: string | null;
          addresses?: Json;
          default_address_index?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          full_name?: string | null;
          phone?: string | null;
          whatsapp?: string | null;
          email?: string | null;
          date_of_birth?: string | null;
          birth_time?: string | null;
          birth_place?: string | null;
          gotra?: string | null;
          rashi?: string | null;
          addresses?: Json;
          default_address_index?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      orders: {
        Row: {
          id: string;
          order_number: string;
          customer_id: string | null;
          guest_email: string | null;
          guest_phone: string | null;
          guest_name: string | null;
          items: Json;
          subtotal: number;
          jewelry_charges: number;
          metal_charges: number;
          certification_charges: number;
          energization_charges: number;
          shipping_cost: number;
          discount: number;
          coupon_code: string | null;
          gst_amount: number;
          total: number;
          shipping_address: Json;
          shipping_method: string | null;
          special_instructions: string | null;
          include_energization: boolean;
          energization_type: string | null;
          ceremony_gotra: string | null;
          ceremony_dob: string | null;
          ceremony_rashi: string | null;
          record_ceremony: boolean;
          payment_method: string | null;
          razorpay_order_id: string | null;
          razorpay_payment_id: string | null;
          razorpay_signature: string | null;
          payment_status: string;
          status: string;
          tracking_number: string | null;
          tracking_url: string | null;
          estimated_delivery: string | null;
          assigned_to: string | null;
          internal_notes: string | null;
          invoice_number: string | null;
          invoice_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          order_number?: string;
          customer_id?: string | null;
          guest_email?: string | null;
          guest_phone?: string | null;
          guest_name?: string | null;
          items: Json;
          subtotal: number;
          jewelry_charges?: number;
          metal_charges?: number;
          certification_charges?: number;
          energization_charges?: number;
          shipping_cost?: number;
          discount?: number;
          coupon_code?: string | null;
          gst_amount?: number;
          total: number;
          shipping_address: Json;
          shipping_method?: string | null;
          special_instructions?: string | null;
          include_energization?: boolean;
          energization_type?: string | null;
          ceremony_gotra?: string | null;
          ceremony_dob?: string | null;
          ceremony_rashi?: string | null;
          record_ceremony?: boolean;
          payment_method?: string | null;
          razorpay_order_id?: string | null;
          razorpay_payment_id?: string | null;
          razorpay_signature?: string | null;
          payment_status?: string;
          status?: string;
          tracking_number?: string | null;
          tracking_url?: string | null;
          estimated_delivery?: string | null;
          assigned_to?: string | null;
          internal_notes?: string | null;
          invoice_number?: string | null;
          invoice_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          order_number?: string;
          customer_id?: string | null;
          guest_email?: string | null;
          guest_phone?: string | null;
          guest_name?: string | null;
          items?: Json;
          subtotal?: number;
          jewelry_charges?: number;
          metal_charges?: number;
          certification_charges?: number;
          energization_charges?: number;
          shipping_cost?: number;
          discount?: number;
          coupon_code?: string | null;
          gst_amount?: number;
          total?: number;
          shipping_address?: Json;
          shipping_method?: string | null;
          special_instructions?: string | null;
          include_energization?: boolean;
          energization_type?: string | null;
          ceremony_gotra?: string | null;
          ceremony_dob?: string | null;
          ceremony_rashi?: string | null;
          record_ceremony?: boolean;
          payment_method?: string | null;
          razorpay_order_id?: string | null;
          razorpay_payment_id?: string | null;
          razorpay_signature?: string | null;
          payment_status?: string;
          status?: string;
          tracking_number?: string | null;
          tracking_url?: string | null;
          estimated_delivery?: string | null;
          assigned_to?: string | null;
          internal_notes?: string | null;
          invoice_number?: string | null;
          invoice_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      jewelry_designs: {
        Row: {
          id: string;
          name: string;
          setting_type: string;
          image_url: string | null;
          description: string | null;
          making_charges: Json;
          estimated_metal_weight: Json | null;
          is_custom: boolean;
          sort_order: number;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          setting_type: string;
          image_url?: string | null;
          description?: string | null;
          making_charges: Json;
          estimated_metal_weight?: Json | null;
          is_custom?: boolean;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          setting_type?: string;
          image_url?: string | null;
          description?: string | null;
          making_charges?: Json;
          estimated_metal_weight?: Json | null;
          is_custom?: boolean;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      energization_options: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          price: number;
          duration: string | null;
          includes: Json;
          includes_video: boolean;
          sort_order: number;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          price: number;
          duration?: string | null;
          includes?: Json;
          includes_video?: boolean;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          price?: number;
          duration?: string | null;
          includes?: Json;
          includes_video?: boolean;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      certification_labs: {
        Row: {
          id: string;
          name: string;
          full_name: string | null;
          extra_charge: number;
          turnaround_days: number;
          sample_cert_url: string | null;
          description: string | null;
          is_default: boolean;
          sort_order: number;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          full_name?: string | null;
          extra_charge?: number;
          turnaround_days?: number;
          sample_cert_url?: string | null;
          description?: string | null;
          is_default?: boolean;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          full_name?: string | null;
          extra_charge?: number;
          turnaround_days?: number;
          sample_cert_url?: string | null;
          description?: string | null;
          is_default?: boolean;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      product_configurations: {
        Row: {
          id: string;
          session_id: string | null;
          customer_id: string | null;
          product_id: string;
          setting_type: string | null;
          design_id: string | null;
          metal: string | null;
          ring_size: string | null;
          chain_length: string | null;
          certification_id: string | null;
          energization_id: string | null;
          gem_price: number | null;
          making_charge: number | null;
          metal_price: number | null;
          metal_weight_grams: number | null;
          gold_rate_per_gram: number | null;
          certification_fee: number | null;
          energization_fee: number | null;
          total_price: number | null;
          status: string;
          order_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          session_id?: string | null;
          customer_id?: string | null;
          product_id: string;
          setting_type?: string | null;
          design_id?: string | null;
          metal?: string | null;
          ring_size?: string | null;
          chain_length?: string | null;
          certification_id?: string | null;
          energization_id?: string | null;
          gem_price?: number | null;
          making_charge?: number | null;
          metal_price?: number | null;
          metal_weight_grams?: number | null;
          gold_rate_per_gram?: number | null;
          certification_fee?: number | null;
          energization_fee?: number | null;
          total_price?: number | null;
          status?: string;
          order_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          session_id?: string | null;
          customer_id?: string | null;
          product_id?: string;
          setting_type?: string | null;
          design_id?: string | null;
          metal?: string | null;
          ring_size?: string | null;
          chain_length?: string | null;
          certification_id?: string | null;
          energization_id?: string | null;
          gem_price?: number | null;
          making_charge?: number | null;
          metal_price?: number | null;
          metal_weight_grams?: number | null;
          gold_rate_per_gram?: number | null;
          certification_fee?: number | null;
          energization_fee?: number | null;
          total_price?: number | null;
          status?: string;
          order_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      consultations: {
        Row: {
          id: string;
          customer_id: string | null;
          expert_id: string | null;
          full_name: string;
          email: string;
          phone: string | null;
          date_of_birth: string | null;
          birth_time: string | null;
          birth_place: string | null;
          life_situation: string | null;
          consultation_type: string | null;
          mode: string | null;
          preferred_date: string | null;
          preferred_time: string | null;
          message: string | null;
          status: string;
          assigned_expert: string | null;
          internal_notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          customer_id?: string | null;
          expert_id?: string | null;
          full_name: string;
          email: string;
          phone?: string | null;
          date_of_birth?: string | null;
          birth_time?: string | null;
          birth_place?: string | null;
          life_situation?: string | null;
          consultation_type?: string | null;
          mode?: string | null;
          preferred_date?: string | null;
          preferred_time?: string | null;
          message?: string | null;
          status?: string;
          assigned_expert?: string | null;
          internal_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          customer_id?: string | null;
          expert_id?: string | null;
          full_name?: string;
          email?: string;
          phone?: string | null;
          date_of_birth?: string | null;
          birth_time?: string | null;
          birth_place?: string | null;
          life_situation?: string | null;
          consultation_type?: string | null;
          mode?: string | null;
          preferred_date?: string | null;
          preferred_time?: string | null;
          message?: string | null;
          status?: string;
          assigned_expert?: string | null;
          internal_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      enquiries: {
        Row: {
          id: string;
          name: string;
          email: string;
          phone: string | null;
          subject: string | null;
          message: string;
          product_id: string | null;
          source: string;
          status: string;
          assigned_to: string | null;
          follow_up_date: string | null;
          internal_notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          email: string;
          phone?: string | null;
          subject?: string | null;
          message: string;
          product_id?: string | null;
          source?: string;
          status?: string;
          assigned_to?: string | null;
          follow_up_date?: string | null;
          internal_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          email?: string;
          phone?: string | null;
          subject?: string | null;
          message?: string;
          product_id?: string | null;
          source?: string;
          status?: string;
          assigned_to?: string | null;
          follow_up_date?: string | null;
          internal_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      reviews: {
        Row: {
          id: string;
          product_id: string;
          order_id: string | null;
          customer_id: string | null;
          customer_name: string;
          customer_location: string | null;
          rating: number | null;
          title: string | null;
          review_text: string | null;
          images: Json;
          is_verified: boolean;
          is_approved: boolean;
          is_featured: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          product_id: string;
          order_id?: string | null;
          customer_id?: string | null;
          customer_name: string;
          customer_location?: string | null;
          rating?: number | null;
          title?: string | null;
          review_text?: string | null;
          images?: Json;
          is_verified?: boolean;
          is_approved?: boolean;
          is_featured?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          product_id?: string;
          order_id?: string | null;
          customer_id?: string | null;
          customer_name?: string;
          customer_location?: string | null;
          rating?: number | null;
          title?: string | null;
          review_text?: string | null;
          images?: Json;
          is_verified?: boolean;
          is_approved?: boolean;
          is_featured?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      coupons: {
        Row: {
          id: string;
          code: string;
          discount_type: string;
          discount_value: number;
          min_order_amount: number;
          max_discount: number | null;
          usage_limit: number | null;
          used_count: number;
          valid_from: string;
          valid_until: string | null;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          code: string;
          discount_type: string;
          discount_value: number;
          min_order_amount?: number;
          max_discount?: number | null;
          usage_limit?: number | null;
          used_count?: number;
          valid_from?: string;
          valid_until?: string | null;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          code?: string;
          discount_type?: string;
          discount_value?: number;
          min_order_amount?: number;
          max_discount?: number | null;
          usage_limit?: number | null;
          used_count?: number;
          valid_from?: string;
          valid_until?: string | null;
          is_active?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      saved_items: {
        Row: {
          id: string;
          customer_id: string;
          product_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          customer_id: string;
          product_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          customer_id?: string;
          product_id?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      admin_activity_log: {
        Row: {
          id: string;
          user_id: string;
          action: string;
          resource_type: string | null;
          resource_id: string | null;
          details: Json | null;
          ip_address: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          action: string;
          resource_type?: string | null;
          resource_id?: string | null;
          details?: Json | null;
          ip_address?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          action?: string;
          resource_type?: string | null;
          resource_id?: string | null;
          details?: Json | null;
          ip_address?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      team_members: {
        Row: {
          id: string;
          role: string;
          name: string;
          is_active: boolean;
          permissions: Json;
          created_at: string;
        };
        Insert: {
          id: string;
          role: string;
          name: string;
          is_active?: boolean;
          permissions?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          role?: string;
          name?: string;
          is_active?: boolean;
          permissions?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      gem_categories: {
        Row: {
          id: string;
          name: string;
          slug: string;
          type: string;
          sanskrit_name: string | null;
          planet: string | null;
          emoji: string | null;
          color: string | null;
          image_url: string | null;
          description: string | null;
          sort_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          type: string;
          sanskrit_name?: string | null;
          planet?: string | null;
          emoji?: string | null;
          color?: string | null;
          image_url?: string | null;
          description?: string | null;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          type?: string;
          sanskrit_name?: string | null;
          planet?: string | null;
          emoji?: string | null;
          color?: string | null;
          image_url?: string | null;
          description?: string | null;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      metals: {
        Row: {
          id: string;
          name: string;
          slug: string;
          purity: string | null;
          price_per_gram: number;
          description: string | null;
          is_active: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          purity?: string | null;
          price_per_gram: number;
          description?: string | null;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          purity?: string | null;
          price_per_gram?: number;
          description?: string | null;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      gold_rate_cache: {
        Row: {
          id: number;
          gold_22k_per_gram: number;
          gold_18k_per_gram: number | null;
          silver_per_gram: number | null;
          source: string | null;
          fetched_at: string;
          manual_override: boolean;
        };
        Insert: {
          id?: number;
          gold_22k_per_gram: number;
          gold_18k_per_gram?: number | null;
          silver_per_gram?: number | null;
          source?: string | null;
          fetched_at?: string;
          manual_override?: boolean;
        };
        Update: {
          id?: number;
          gold_22k_per_gram?: number;
          gold_18k_per_gram?: number | null;
          silver_per_gram?: number | null;
          source?: string | null;
          fetched_at?: string;
          manual_override?: boolean;
        };
        Relationships: [];
      };
      notification_log: {
        Row: {
          id: string;
          type: string;
          recipient: string;
          template: string | null;
          context: Json | null;
          status: string;
          error_message: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          type: string;
          recipient: string;
          template?: string | null;
          context?: Json | null;
          status?: string;
          error_message?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          type?: string;
          recipient?: string;
          template?: string | null;
          context?: Json | null;
          status?: string;
          error_message?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}

// Convenience type aliases
export type Product = Database['public']['Tables']['products']['Row'];
export type ProductInsert = Database['public']['Tables']['products']['Insert'];
export type Expert = Database['public']['Tables']['experts']['Row'];
export type CustomerProfile = Database['public']['Tables']['customer_profiles']['Row'];
export type Order = Database['public']['Tables']['orders']['Row'];
export type OrderInsert = Database['public']['Tables']['orders']['Insert'];
export type JewelryDesign = Database['public']['Tables']['jewelry_designs']['Row'];
export type EnergizationOption = Database['public']['Tables']['energization_options']['Row'];
export type CertificationLab = Database['public']['Tables']['certification_labs']['Row'];
export type ProductConfiguration = Database['public']['Tables']['product_configurations']['Row'];
export type Consultation = Database['public']['Tables']['consultations']['Row'];
export type Enquiry = Database['public']['Tables']['enquiries']['Row'];
export type Review = Database['public']['Tables']['reviews']['Row'];
export type Coupon = Database['public']['Tables']['coupons']['Row'];
export type SavedItem = Database['public']['Tables']['saved_items']['Row'];
export type TeamMember = Database['public']['Tables']['team_members']['Row'];
export type GoldRateCache = Database['public']['Tables']['gold_rate_cache']['Row'];
export type NotificationLog = Database['public']['Tables']['notification_log']['Row'];
export type GemCategoryRow = Database['public']['Tables']['gem_categories']['Row'];
export type GemCategoryInsert = Database['public']['Tables']['gem_categories']['Insert'];
export type Metal = Database['public']['Tables']['metals']['Row'];
export type MetalInsert = Database['public']['Tables']['metals']['Insert'];
